### ISSUE TITLE
ckeditor 4.5.5 loading tree times css

### ISSUE THREAD

**Issue by qssocial** [WBCE/WebsiteBaker_CommunityEdition#104]
1. Ckeditor loading tree times css !.
2. CKEditor uses the functions "LoadOnFly" (we do not have it) for
loading css.

Therefore, "backend.css" not worked properly.
I added to ckeditor.php in "private function init ()" loading of
"backend.css" and removed ln 360
" // $ this-> loadBackendCss ();"
Please see if it works correctly.
https://github.com/qssocial/WebsiteBaker_CommunityEdition

**Comment by NorHei** [comment]
I already applied your Patch :-)
