### ISSUE TITLE
Updating droplets

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#105]
The new droplets version has the version no. 1.8, the old one 1.75 (and unfortunately not 1.7.5 what was meant I guess), so updating droplets fails with an "already installed" error.
I would propose altering the module version number to something higher, e.g. 1.80 or 2.0

**Comment by webbird** [comment]
Set it to 2.0.0 to make clear that future version should have 3-part-version-numbers.
