### ISSUE TITLE
Not possible to create new droplets

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#107]
A succesful message and a debug output pops out, but the new droplet does not shine up in the list

Warning: Cannot modify header information - headers already sent by (output started at /.../modules/phplib/classes/phplib/template.inc:668) in /.../modules/droplets/save_droplet.php on line 35

Notice: Undefined variable: droplet_id in /.../modules/droplets/save_droplet.php on line 73

(Furthermore: error reporting is switched to "none", so why do this messages occur? Strange...)

**Comment by NorHei** [comment]
#97

**Comment by instantflorian** [comment]
For me it looks as if the save_droplet.php doesn't recieve the droplet id due to this idkey stuff and therefor can't save the droplet. That's a pity.

**Comment by NorHei** [comment]
You are perfectly right.

New Droplets are generated in  add_droplet.php.

In tools.php  line 29 they are deleted again, always ...
So the query in line 131 cannot return any values for this droplet as
its already deleted .
So the hidden field cannot be populated and no droplet_id is sent to save.

So the Droplet is created , deleted , and then tried to edit ...

I added an if clause that only deletes the empty droplets on normal tool
view, whithout do=something. This should do it.  Hopefully.

6a27524563287eba666e7b4fd9ea386e5f86aba5
