### ISSUE TITLE
Browser detect backend als being Windows_1250 charset 

### ISSUE THREAD

**Issue by NorHei** [WBCE/WebsiteBaker_CommunityEdition#109]
If you use firefox and go to extra -> pageinformation. 
It says charset is Windows-1250 in backend .

Any ideas ?

**Comment by webbird** [comment]
What's in the HTML source?

**Comment by NorHei** [comment]
MEta is ok , WBCE default template

Meta says UTF-8
I send you a link to a test version .




Am 26.01.2016 um 10:40 schrieb Bianka Martinovic:
> What's in the HTML source?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WBCE/WebsiteBaker_CommunityEdition/issues/109#issuecomment-174926825>.
>

-- 
Norbert Heimsath
Mergelstraße 25
45478 Mülheim an der Ruhr
Tel: 0208 55792

**Comment by webbird** [comment]
There used to be a setting in FF to let you override the encoding set by the page header. Look at about:config. Also try a different browser - if it has the right encoding, it's just a FF issue, not a WBCE issue.

**Comment by webbird** [comment]
Try to set the browser.menu.showCharacterEncoding pref to true on the about:config page and drag the "Text encoding" menu item to your menu.

**Comment by webbird** [comment]
Checked my local WBCE Dev installation, it shows UTF-8 as encoding, so I'm sure it's a local configuration problem.

**Comment by NorHei** [comment]
strange... i try on a nother webspace ..

Am 26.01.2016 um 11:23 schrieb Bianka Martinovic:
> Checked my local WBCE Dev installation, it shows UTF-8 as encoding, so
> I'm sure it's a local configuration problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WBCE/WebsiteBaker_CommunityEdition/issues/109#issuecomment-174944650>.
>

-- 
Norbert Heimsath
Mergelstraße 25
45478 Mülheim an der Ruhr
Tel: 0208 55792

**Comment by NorHei** [comment]
Not able to reproduce this on other webspaces ...
