### ISSUE TITLE
Error upgrading from WB to WBCE: Use of undefined constant WB_SECFORM_TIMEOUT

### ISSUE THREAD

**Issue by digitalbricks** [WBCE/WebsiteBaker_CommunityEdition#110]
While upgrading WB to WBCE via `upgrade-script.php` i got serveral PHP notices:

> Use of undefined constant WB_SECFORM_TIMEOUT - assumed 'WB_SECFORM_TIMEOUT' in /framework/initialize.php

Because this error message probably prevents other scripts (including the `initialize.php`) from sending redirect headers via `header()` i was unable to login into the backend. I ended in an upgrade-script-backend-login-upgrade-script-loop.

Digging through the code i found several usages of the constant `WB_SECFORM_TIMEOUT` but no `define()` statement for it. So it seems that `WB_SECFORM_TIMEOUT` is indeed not defined.

My quick an dirty fix was to add `define ('WB_SECFORM_TIMEOUT', 3600);` in the first lines of `/framework/initialize.php`. So i got no notices any more and was able to successfully upgrade WB (2.8.1) to WBCE.

**Comment by NorHei** [comment]
What Version of WB you where using ?

**Comment by digitalbricks** [comment]
It was an upgrade from WB 2.8.1 to WBCE 1.1.3.

**Comment by digitalbricks** [comment]
Let me add an update: As i posted initially, i thought adding my quick and dirty fix helped me upgrading WB successfully to WBCE. But it turns out: It didn't. While working on the backend i got several warnings "Sicherheitsverletzung! Zugriff verweigert!" and where unable to install themes and modules or change system settings. I retried it a couple of times but ended always at the same point: "Sicherheitsverletzung! Zugriff verweigert!". So finally i did a clean install of WBCE and the copied DB tables and files manually from the old WB into the WBCE install. That was a pain but at the end I got a working WBCE with contents and modules of the old WB install. So in result i can state: Upgrading WB 2.8.1 to WBCE 1.1.3. seems to not work at the moment.

**Comment by NorHei** [comment]
Hi again


Hmm ... so for now it seems to be best to  update so 2.8.3 first and 
then to WBCE.

Going to fix this issues as soon as possible. Seems like testers never 
upgraded from 2.8.1.

I need to setup a testing enviroment to to Reproduce this but it will 
take me a Day to three to fix this.

Thanks a lot for reporting! I was on vacation, so it did not reach me 
immediately .




Am 21.02.2016 um 16:37 schrieb digitalbricks:
> Let me add an update: As i posted initially, i thought adding my quick
> and dirty fix helped me upgrading WB successfully to WBCE. But it turns
> out: It didn't. While working on the backend i got several warnings
> "Sicherheitsverletzung! Zugriff verweigert!" and where unable to install
> themes and modules or change system settings. I retried it a couple of
> times but ended always at the same point: "Sicherheitsverletzung!
> Zugriff verweigert!". So finally i did a clean install of WBCE and the
> copied DB tables and files manually from the old WB into the WBCE
> install. That was a pain but at the end I got a working WBCE with
> contents and modules of the old WB install. So in result i can state:
> Upgrading WB 2.8.1 to WBCE 1.1.3. seems to not work at the moment.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WBCE/WebsiteBaker_CommunityEdition/issues/110#issuecomment-186845800>.
>

-- 
Norbert Heimsath
Mergelstraße 25
45478 Mülheim an der Ruhr
Tel: 0208 55792

**Comment by NorHei** [comment]
WB 2.8.1 does not have secureform, thats the reason why initialize fails on that constant . 
So setting the time interval to 3600  a good idea , but i guess a better place would have been 
Line 134  right after 
`  // include required scripts and setup admin object`
Insert a 
`define ("WB_SECFORM_TIMEOUT", 7200);`

As 3600 is a pretty short interval for Forms to run out. You can even define a longer time Interval in the Securefor Switcher in the Admintools. And i guess that it was the short time interval till forms time out that cause the security warnings. 

But i still going to test this .

**Comment by NorHei** [comment]
Zumindest bei meinem Lokalen test läuft das so , ich hab nochmal jemand gebeten das zu testen .

**Comment by digitalbricks** [comment]
As i understand WB versions from 2.8.2. do have this constant set. So maybe it would be better to wrap the definition in a condition:

```php
if(!defined("WB_SECFORM_TIMEOUT"){
   define ("WB_SECFORM_TIMEOUT", 7200);
}
```

**Comment by NorHei** [comment]
Evaki was so kind to do another test , and it seems to run smooth now. 

If the constant is set before calling config and initialize there is no conflict as initialize sets this const from DB but only if its not already set. So the "if (defined)"  is already there in the settings loader.   

The settings loader is one of the new parts of WBCE so its design is far more robust than the old code and made for interactig whith manual overrides like this one.  

If you run into a problem whith Secureform again you might try to go to 
Admintools->Secureform Switcher  
and reset settings to default.

**Comment by NorHei** [comment]
Do you have an installlable Package of that ond WB 2.8.1 , there seem to be several versions...

**Comment by digitalbricks** [comment]
Thank yo for the explanation! Make sense.

I browsed through my legacy data and found an old WB 2.8.1 installation package. If you wanna try it out, you can download it here: [https://www.dropbox.com/s/2elsrtlqs2kgb9d/WebsiteBaker_2.8.1.zip?dl=0](https://www.dropbox.com/s/2elsrtlqs2kgb9d/WebsiteBaker_2.8.1.zip?dl=0)

**Comment by NorHei** [comment]
We made a fix vor this and a planed release , but then The WB security issue came up so we need to make a new release soon , so we dont do a big publish for this one . 

https://github.com/WBCE/WebsiteBaker_CommunityEdition/releases/tag/1.1.4

Closing this for now
