### ISSUE TITLE
Internal [wblinkXYZ] not replaced in template

### ISSUE THREAD

**Issue by digitalbricks** [WBCE/WebsiteBaker_CommunityEdition#111]
Internal links placed in a template using the `[wblink]`-Tag aren't replaced while rendering the document. I used this from time to time in order to place links to fixed pages, such as imprint, terms of service etc. in the footer of the page:

```html
<a href="[wblink6]">Imprint</a>
```

But in WBCE this tags aren't replaced any more and so the  `[wblink]`-Tag keeps present in the link.

Yes i know, i could use multiple menus for placing some links in the footer, but using the [wblink] syntax was a nice way to add these links without the use of (sometimes clunky) `show_menu2()`. Would be nice to see this functionality again in an upcoming version of WBCE.

**Comment by digitalbricks** [comment]
Ah, wait wait wait! I got the point: In order to get this function in WBCE we need to install the **Output Filter Dashboard (PPF Dashboard)** and then load the **WBLink** output filter there. After that, `[wblink]` tags will be replaced by actual links like we know it from WB or LEPTON. Okay, no bad solution – you only have to know :-)

**Comment by digitalbricks** [comment]
That's strange: I turns out, that the built in output filter works well on on clean install without the need of the Output Filter Dashboard module. Browsing a bit through the code if found, that in the `index.php`, found in the root of the WBCE install, the "old" output filter processing is skipped if the PHP constant `WB_SUPPRESS_OLD_OPF` is set. On a clean install this constant is not defined and so the output filter is processed. On my install upgraded from WB 2.8.3. the constant `WB_SUPPRESS_OLD_OPF` **is defined** with the value 0 (as string) and so the built in filter processing is skipped.

And now the really freaky thing: I was unable to find a `define()`statement for `WB_SUPPRESS_OLD_OPF` in the files and the database of the (upgraded from WB) install. In fact, the string "WB_SUPPRESS_OLD_OPF" only occurs inside the `index.php` in the `if()` condition were this constant is checked for presence. What in the world is responsible for the constant `WB_SUPPRESS_OLD_OPF` being set?

It also turns out that the table responsible for the built in output filter settings (PREFIX_mod_output_filter) was not present in the upgraded install. But importing this table manually from a clean install doesn't fix the problem (and also does not explain how `WB_SUPPRESS_OLD_OPF is set).

**Comment by NorHei** [comment]
Can i take a look at that problem directly.
Mailto norbert@heimsath.org . 

Somehow notifications here on git are not relieable ....

**Comment by digitalbricks** [comment]
@HorHei Because i cannot give you access to the work-in-progress project at this point of development (because of some unconfirmed and yet confidential company names) i tried to prepare you a "clean" copy. So i installed a WB 2.8.3 locally (same source files like in the real project) and updated it to WBC 1.1.3. But this time everything concerning this issue is okay – `WB_SUPPRESS_OLD_OPF` is **not** defined and the output filters processes the content and replaceing `[wblink##]` tags. 

So i still have no idea what causes `WB_SUPPRESS_OLD_OPF` to be defined in my project and causes the filters to bypass. Anyway,  i can handle this at the moment with the workaround of the output filter dashboard. 

You may close this ticket.

**Comment by digitalbricks** [comment]
**I finally found it**
In my project (upgraded from WB 2.8.3) there was a row in table `[prefix]_settings` with _setting_id_ 60, _name_ wb_suppress_old_opf and _value_ 0. Cleaning out the "0" doesn't make any difference but deleting the entire row renables the output filter because `WB_SUPPRESS_OLD_OPF` is not set anymore. Yeh!

Having compared the the table `[prefix]_settings` with that one from a clean install, it seems that there is no such setting in WBCE. So i assume it's uncritical to delete this row.

**Comment by NorHei** [comment]
wb_suppress_old_opf should not be set as a default ...

**Comment by NorHei** [comment]
Is it possible you installed the Development Version instead of the Stable one ?

1.1.x Branch does not have this value

**Comment by digitalbricks** [comment]
Hmmm... maybe thats the only explanation for this. I indeed accidentally did an upgrade using the master branch from github, but then i noticed this failure, deleted all and used the _WebsiteBaker_CommunityEdition-1.1.3.zip_ from the WBCE website. At least, i am fairly sure i did this ;-) Is there a way to retrieve the version number or an clue wich version is actually in use?

**Comment by NorHei** [comment]
have a look in /admin/interface/version.php
To me it feels like a mixture , as 1.1.3 is not aware of this constant. At least the filter Module must be a 1.2.x one, possibly you found a bug in 1.1.2 :-)

**Comment by NorHei** [comment]
Back later in the evening .

**Comment by digitalbricks** [comment]
Smells like 1.1.3:

```php
if (!defined('WB_URL')) {
    header('Location: ../index.php');
    exit(0);
}

// set WBCE version and release tag
define('NEW_WBCE_VERSION', '1.1.3');
if (!defined('WBCE_VERSION')) {
    define('WBCE_VERSION', NEW_WBCE_VERSION);
}

define('NEW_WBCE_TAG', '1.1.3');
if (!defined('WBCE_TAG')) {
    define('WBCE_TAG', NEW_WBCE_TAG);
}

// Legacy: WB-classic
if (!defined('VERSION')) {
    define('VERSION', '2.8.3');
}

if (!defined('REVISION')) {
    define('REVISION', '1641');
}

if (!defined('SP')) {
    define('SP', 'SP4');
}

```

**Comment by NorHei** [comment]
Again 1.1.3 is not aware of this constant . 

But if deleting the constant from DB does do the job you can leave the installation as it is.

If you like to experiment , you can delete the output_filter module and copy a clean one from your 1.1.3 Zipfile .  

Btw, yess you found a bug in 1.2.x :-))

**Comment by NorHei** [comment]
stop it replacing filter does not help ...

**Comment by NorHei** [comment]
Deleting the DB entry is 100% sufficient . 
Your files are 1.1.3 . 

Only DB was not overwritten . 
And 1.1.3 already allows manual override of Outputfilters in the config file . 
whith 
define("WB_SUPPRESS_OLD_OPF" , true);
or
define("WB_SUPPRESS_OLD_OPF" , false);
to activate em again. 

But i WBCE the value is set in the Database Settings and the value is 0 . 
So the if then in 1.1.3 fails .
if (!defined("WB_SUPPRESS_OLD_OPF") or  WB_SUPPRESS_OLD_OPF===false){

In 1.2.x the line is 
if (!defined("WB_SUPPRESS_OLD_OPF") or !WB_SUPPRESS_OLD_OPF){
this has no problem whith a 0 value. 

So i am pretty sure the DB is the one from 1.2.x .

As the DBs are no other differences besides from a few settings , i would keep that install after deleting the Setting in the DB.

**Comment by digitalbricks** [comment]
@NorHei Thank you for your investigations!
