### ISSUE TITLE
"SEO Tool for WebsiteBaker CMS" not working after upgrading from WB 2.8.3

### ISSUE THREAD

**Issue by digitalbricks** [WBCE/WebsiteBaker_CommunityEdition#112]
After upgrading a site from WB 2.8.3 to WBCE 1.1.3. i noticed that the admin tool is not working (but its working on a clean install). I got the follwing messages in the js console:

> unexpected token ;
> not defined constant MODULE_URL

Having a look at the HTML source i found this:

```html
<script type="text/javascript" language="javascript">
	var CLICK2EDIT = "Click to edit inline";
	var CANCEL     = "Cancel";		//'Cancel',
	var MODULE_URL = "http://192.168.2.5/wbce/modules/wbSeoTool";
	var sCounterText = '<span><strong>[%2]</strong><br /> <nobr><small>(</small>%1 <small>chars left)</small></nobr></span>';
	var iTitleCount_optimum = ;
	var iTitleCount_minimum = ;
	var iDescriptionCount_optimum = ;
	var iDescriptionCount_minimum = ;
	var iDescriptionCount_use = ;
	var iTitleCount_use = ;
</script>
```

As you can see, the values for `iTitleCount_optimum`, `iTitleCount_minimum`, `iDescriptionCount_optimum`, `iDescriptionCount_minimum` such as `iDescriptionCount_use` and `iTitleCount_use` where empty. This lead to the `unexpected token ;` message and because the script fails, `MODULE_URL` could also not be set.

Unfortunately, i was unable to set these missing values in the settings panel of this admin tool because the values i entered where not stored.

**So in fact there seems to be two errors:**
1. there are no fallback values set if a setting is not present in the `tool.php` of the admin tool
2. values entered under "advanced settings" in the admin tools arn't stored

As is said above, this behavior only affects my upgraded website. The tools works smooth on a clean install.

**Comment by NorHei** [comment]
Have you tried to uninstall the tool and install a fresh one ?
Maybe sometthing in the upgrade process of the module went wrong ?

**Comment by NorHei** [comment]
Given Stefek a note about this , he is the author .

**Comment by digitalbricks** [comment]
@NorHei Good point! Uninstalling and reinstalling the module (0.5.0 from the WB addon repository) did the trick.
