### ISSUE TITLE
Have a look after SM2 and XHTML(Strict) HTML5 rendering. 

### ISSUE THREAD

**Issue by NorHei** [WBCE/WebsiteBaker_CommunityEdition#114]
http://forum.wbce.org/viewtopic.php?pid=3649#p3649

Target="_blank" is forbidden in strict XHTML for example.

**Comment by webbird** [comment]
I'm interested in this for BC, too, so it would be great to do it together. Especially as there are several different versions (WB Classic, LEPTON, BC).

**Comment by NorHei** [comment]
Thats great!

Things that are planned on WBCE side for SM(2/3)

1. Some kind of templating mechanism:
  a. Maybe simply return the pages array whith all data , and let
     the templatebuilder handle it manually.
  b. Allow to store a set of templatevariables in a File , so instead
     of adding the formating information to the function, you can call a
     file whith premade options.
  c. Possibly allow fully styled PHP templates to render the output.

2. Adding several vars to be displayed , Page image Page Icon, ...

3. Try to make the Template Language of SM2 fully recursive (condition 
in condition ... ), or 1.c.

4. As a result of the first 3 it should be easy to make templates that 
render either a certain (X)HTML Standard or possibly multiple Standards 
depending on a Rendering Konstant.

5. Make it possible to all it as a CLass so there is no need for endles 
option chains if you only want to change the last parameter.

Possibly we won't reach all of this goals in the first step, but we will 
see :-)

Are there any other interesting improvements in possibly forgot ?

Thinking about all this stuff i guess we better go for a SM3 :-)





-- 
Norbert Heimsath
Mergelstraße 25
45478 Mülheim an der Ruhr
Tel: 0208 55792

**Comment by digitalbricks** [comment]
To be honest: How many sites out there are using XHTML strict as doctype? I think in the age of HTML5 and upcoming versions, XHTML in general and its strict variant seems to be a bit outdated.

**Comment by NorHei** [comment]
In the age of HTML5 :-)

There is not a single HTML Filter Lib (Like HTML Purifyer)that FULLY 
supports HTML5 .

Displaing videos whith HTML5 there still is not a single video format 
thats suppotred by all browsers.

As Evaki Stated in the Forum there are quite q few publishing companies 
that use XHTML Stict as a format for their Data.

And if its template based it does not matter at all as you simply can 
make your own.

**Comment by NorHei** [comment]
Having an eye on this when rewriting SM2 .

**Comment by NorHei** [comment]
Seems like the best soloution is to build you own rendering variables for the menu.
As SM2 offers this option i will close this for now.
