### ISSUE TITLE
Installer should be able to use Github Zips 

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#12]
Currently, Modules which are hosted at Github have to be unzipped and zipped again to get rid of the subdirectory with the module name, because the installer requires a zip w/o a subdirectory.
Solution could be unzipping the files to the temp directory first and then moving the actual module directory (which can be identified by the containing info.php) to /modules/.

**Comment by cwsoft** [comment]
Will take care about implementing the advanced ZIP support for Addons.

**Comment by cwsoft** [comment]
Need to rework the check for the first addon folder containing an info.php file. Actual implementation checks last 8 characters in file path. This may lead to false positive if filename ends with info.php like "phpinfo.php" or "mysqlinfo.php". Easy to fix.
