### ISSUE TITLE
account/email.php Line 30ff double escaping?

### ISSUE THREAD

**Issue by NorHei** [WBCE/WebsiteBaker_CommunityEdition#121]
Have an eye on this , for now i commentet out the line whith add slashes

**Comment by qssocial** [comment]
you want to save an incorrect email?
// Validate values
	if($rowset->numRows() == 0) {
		$error[] = $MESSAGE['PREFERENCES_CURRENT_PASSWORD_INCORRECT'];
	}else {
		if(!$wb->validate_email($email)) {
			$error[] = $MESSAGE['USERS_INVALID_EMAIL'];
		**// not this }else {**
			**// $email = $wb->add_slashes($email);**
// Update the database
			$sql = "UPDATE `".TABLE_PREFIX."users` SET `email` = '".$database->escapeString($email)."' WHERE `user_id` = ".$wb->get_user_id();
			$database->query($sql);
			if($database->is_error()) {
				$error[] = $database->get_error();
			} else {
				$success[] = $MESSAGE['PREFERENCES_EMAIL_UPDATED'];
				$_SESSION['EMAIL'] = $email;
			}
		}
	}

**Comment by NorHei** [comment]
been really tired when editin this i guess 
f532398

thanks !
