### ISSUE TITLE
SQL Injection (account/preferences.php) - please add FTAN 

### ISSUE THREAD

**Issue by qssocial** [WBCE/WebsiteBaker_CommunityEdition#123]
https://www.htbridge.com/advisory/HTB23296
preferences_form.php
after line 38 add $ftan = $wb->getFTAN();
line 144
// Insert language headings
$template->set_var(array(
    'FTAN' => $ftan,
    'HEADING_MY_SETTINGS' => $HEADING['MY_SETTINGS'],
    'HEADING_MY_EMAIL' => $HEADING['MY_EMAIL'],
    'HEADING_MY_PASSWORD' => $HEADING['MY_PASSWORD'],
)

template.html
change 
form name="details" action="" method="post"
{FTAN}
form name="email" action="" method="post"
{FTAN}
form name="password" action="" method="post"
{FTAN}

details.php
email.php
password.php
add:
	if (!$wb->checkFTAN()) {
		$wb->print_error($MESSAGE['GENERIC_SECURITY_ACCESS'],
		                    WB_URL );
	}

Thank you
Krzysztof

**Comment by NorHei** [comment]
edafe34
and
1140097 
and thanks a lot !

**Comment by NorHei** [comment]
Maybe, you like to build this functionality into a real page module ?
That would be great!!

**Comment by qssocial** [comment]
If I have time - yes.
Currently I am doing Blog module, with categories, tags, photos, downloads and users rights to the posts and media. I need this for my clients websites. My version WB does not use pages and short.php. This year I have to a lot to change, to adapt my WB to the needs of customers. I must also write a program for Windows and Mac to send large amounts of e-mails from the WB (typically communication xml, json, csv - free as part of my WB).
