### ISSUE TITLE
admin/pages/section.php - not loaded section with multifunctionals (ex. tool,page,snippet,preinit)

### ISSUE THREAD

**Issue by qssocial** [WBCE/WebsiteBaker_CommunityEdition#125]
line 430 admin/pages/section.php
$sql .= 'WHERE `type` = "module" AND `function` = "page" AND `directory` != "menu_link" ';

change for 
$sql .= 'WHERE `type` = "module" AND `function` LIKE \'%page%\' AND `directory` != "menu_link" ';

Krzysztof

**Comment by NorHei** [comment]
I really like it , that you deliver problems together whith a solution!
Thanks !

**Comment by NorHei** [comment]
5417462
