### ISSUE TITLE
Strict error in frontend::get_page_details vs wb::get_page_details

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#127]
Strict Standards: Declaration of frontend::get_page_details() should be compatible with wb::get_page_details($page_id, $backLink = 'index.php') in /.../framework/class.frontend.php on line 17

This error occurs in the frontend of pages which are build with the current development version, although the strict workaround is active and I'm not sure wether mysql strict is in use in my testing enviroment (I guess it's not). But maybe I'm mixing up different "strict" standards...

**Comment by NorHei** [comment]
Thats not an DB issue , thats a s me movig some methods around between class admin and class wb.

I wonder why i don' get those errors....

**Comment by NorHei** [comment]
should be fixed for now. 

423647d
