### ISSUE TITLE
admin/groups/index.php change: function` = "%page%"

### ISSUE THREAD

**Issue by qssocial** [WBCE/WebsiteBaker_CommunityEdition#128]
line 132
$result = $database->query('SELECT * FROM `'.TABLE_PREFIX.'addons` WHERE `type` = "module" AND `function` = "%page%" ORDER BY `name`');

change to
$result = $database->query('SELECT * FROM `'.TABLE_PREFIX.'addons` WHERE `type` = "module" AND `function` LIKE "%page%" ORDER BY `name`');

Krzysztof

**Comment by NorHei** [comment]
Thanks alot !

**Comment by NorHei** [comment]
16529d5
