### ISSUE TITLE
Multiple Warning

### ISSUE THREAD

**Issue by qssocial** [WBCE/WebsiteBaker_CommunityEdition#129]
PHP 5.38, Windows 10

Warning: array_merge(): Argument #3 is not an array in wbSeoTool\view_pageTree.php on line 57
WB SEO Tool

 WebsiteBaker Visitor statistics
strange not take table !!!
"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1SELECT sum(user) visitors, sum(view) visits FROM
"
overview Fatal error: Call to a member function fetchRow() on a non-object in \modules\wbstats\class.stats.php on line 70
visitors
Fatal error: Call to a member function fetchRow() on a non-object in \modules\wbstats\class.stats.php on line 155
history
Fatal error: Call to a member function fetchRow() on a non-object in \modules\wbstats\class.stats.php on line 233

Strange
 Page Cloner - try duplicate if public with no subpages
Table 'wb37.lep_mod_wysiwyg_admin' doesn't exist ????

Strict Standards: Declaration of frontend::get_page_details() should be compatible with wb::get_page_details($page_id, $backLink = 'index.php') in framework\class.frontend.php on line 17
Just change for compatibility
 public function get_page_details($page_id = 0, $backLink = 'index.php')

http://stackoverflow.com/questions/21092605/php-strict-standards-declaration-of-should-be-compatible

**Comment by NorHei** [comment]
The last one was already reported and fixed . 
#127

The other ones o take a look :-)

**Comment by NorHei** [comment]
Ok, first warning done d4fd7fa

**Comment by NorHei** [comment]
About wbstats :
Hopefully i caught all of those global vars now.  
e23500d

**Comment by NorHei** [comment]
About page cloner.
I can not reproduce this one cloned about a dozen pages. 

lep_mod_wysiwyg_admin

Sounds like a Lepton module to me ?

**Comment by NorHei** [comment]
Can i close this ?

**Comment by qssocial** [comment]
yes
