### ISSUE TITLE
Change superuser concept

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#13]
Instead of checking "user has userid == 1"  => superadmin it should be "user is in group_id == 1" => superadmin, so this way it could be easily managed to whom access to the advanced options should be granted. 
http://forum.wbce.org/viewtopic.php?id=15

**Comment by webbird** [comment]
Postponed to some later version

**Comment by NorHei** [comment]
Hopefully i got em all , testing ran  smoth here on local .

**Comment by NorHei** [comment]
As it seems that noone had any problems so far , i am closing this.
