### ISSUE TITLE
 \admin\groups\groups.php  sql error

### ISSUE THREAD

**Issue by qssocial** [WBCE/WebsiteBaker_CommunityEdition#130]
Fatal error: Call to a member function numRows() on a non-object in \admin\groups\groups.php on line 87
$result = $database->query('SELECT * FROM `' . TABLE_PREFIX . 'addons` WHERE `type` = "module" AND  LIKE "%page%"  ORDER BY `name`');

Change to
$result = $database->query('SELECT * FROM `' . TABLE_PREFIX . 'addons` WHERE `type` = "module" AND  `function` LIKE "%page%"  ORDER BY `name`');

**Comment by NorHei** [comment]
I love bug reports whith solutions!! 7a25fc0

Thanks!
