### ISSUE TITLE
Installations fails with warning

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#131]
WBCE 1.2 alpha from today
PHP 7.0.5
After clicking on "Install WBCE"

Warning: Declaration of admin::get_page_details($page_id, $backLink = 'index.php') should be compatible with wb::get_page_details($page_id = '', $backLink = 'index.php') in /.../framework/class.admin.php on line 19

Warning: Cannot modify header information - headers already sent by (output started at .../framework/class.admin.php:19) in /.../framework/class.login.php on line 99

**Comment by qssocial** [comment]
class.admin 312
    public function get_page_details($page_id, $backLink = 'index.php')
class.wb 601
public function get_page_details($page_id="", $backLink = 'index.php')

**Comment by NorHei** [comment]
hey you where faster .... :-)

33d3eb3

I have to look for another way to simplyf those classes , as i want to get rid of those Frontend.->Backend  differences ..
