### ISSUE TITLE
When not logged in tool.php throws error instead of redirecting to login screen

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#132]
if a visitor calls http://domain.tld/admin/settings/tool.php
he is not redirected to the login screen but sees
Notice: Undefined index: MODULE_PERMISSIONS in /.../framework/class.tool.php on line 124
Warning: implode(): Invalid arguments passed in /.../framework/class.tool.php on line 124
Warning: Cannot modify header information - headers already sent by (output started at /.../framework/class.tool.php:124) in /.../framework/class.admin.php on line 34

**Comment by NorHei** [comment]
I am on it :-)

**Comment by NorHei** [comment]
Should be ok now !
