### ISSUE TITLE
optimize options/system settings

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#135]
"WYSIWYG Stil" should be removed (its not used)
"Intelligente Anmeldung" should be removed (its not used)
The value for "Weiterleitung nach" should be set to 500 (1500 is usually annoying I think)

Btw., since the Maintainance Mode switch is available here, the MM admin tool should be removed

**Comment by NorHei** [comment]
As we decided to do the new BE in 2.0 i think we simply can leave this , or better put this on a 2.0 Milestone.
Concerning the wait time, personally i even would prefer a longer time if there are any error messages. 

MM tool is 2.0 too we reset the adminpages to old system for 1.2.x

**Comment by instantflorian** [comment]
Changed milestone.
The waiting time is in most cases (at least for me) annoying, and there should be no errors ;-) for development environment it's too short (therefor you can deactivate the redirect completely), but when everything works well these 1500 miliseconds feel like eternity and as WBCE would be a slow CMS (what it isn't).

**Comment by NorHei** [comment]
maybe i take a look if i can add a multiplyer for error messages 
So errors are displayed 3 to 5 times longer than ok messages .. Ill take a look

**Comment by NorHei** [comment]
Maintainance Mode removed 
"WYSIWYG Stil" removed!
500 miliseconds Set as default
Errors no longer redirect, you need to push back button. 
"Intelligente Anmeldung" stays in for now , maybe got some nice idea whith this
