### ISSUE TITLE
Minor enhancements for Adv. Backend Theme

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#136]
WebsiteBaker CE in the title should be replaced with WBCE
Maybe it would be helpful to display the PHP version somewhere too
Form autofill should not be disabled (/templates/advancedThemeWbFlat/jquery/jquery-plugins.js
At the dashboard, the FA icon for admin tools is missing

**Comment by NorHei** [comment]
Replaced whith WBCE
PHP Version showing near WBCE version in flat theme. Hat to take a look at Argos too . 
Dashboard FA icon restored.

**Comment by NorHei** [comment]
```
//$('form').attr('autocomplete', 'off');
```

Autocomplete off is commented out , so basically i see no problem ?? Maybe deactivated in browser ?

**Comment by instantflorian** [comment]
Sorry, I have changed the autocomplete setting in a commit some days ago:
https://github.com/WBCE/WebsiteBaker_CommunityEdition/commit/a18e7253b101b88e42d1fe6926fc96bb8091de5b

**Comment by NorHei** [comment]
No problem  :-) can we close this then ?
