### ISSUE TITLE
Get rid of singletab "security"

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#14]
We all should take a look into removing and replacing the whole Singletab - Multitab desaster whith something that really works.
1. The FTAN / IDKEY beast still got some bugs.
2. The whole BE needed to be changed to get the silly Singletab thing to work. This should be undone as this is unecessary complexity and makes BE development much harder.
3. This beast does not work in the frontend.
 
Disadvantage is, that its a lot of work :-)

**Comment by NorHei** [comment]
Done in next release !
