### ISSUE TITLE
Users not deleted properly

### ISSUE THREAD

**Issue by digitalbricks** [WBCE/WebsiteBaker_CommunityEdition#146]
Hello community,

i found a bug in WBCE 1.1.6, clean install.

Steps to reproduce:

1. Create a new user group
2. Create a new user and assign to the previously created user group
3. Delete the user just created
4. Try to delete the user group created in step 2

You will see an error claiming that this group still has user assigned to. If you switch back to the user management, there is no user assigned to this group any more – so it seems the user is deleted properly. But that's not the case, as the systems criticised on the group deletion attempt. Checking the MySQL database, table [PREFIX]_user, you will see that the user still exists there.

So it seems WBCE (and maybe WB?) does not delete users properly, but it modifes the DB entry in a weird way so that the user disappears in the user list.

Kind regards
André

**Comment by NorHei** [comment]
If you delete users they are set inactive on the first step, inactive users can be shown by clicking on the little icon next to the text "List Options Users active" . So the user may still be there :-)

Can you please check this .

**Comment by NorHei** [comment]
Could not reproduce this problem ... exept when i don't delete the inactive user.

**Comment by digitalbricks** [comment]
Thanks for the explanation! Haven't checked this yet but it's probably what you described. 
But in this case the delete-user-button should have a different label, not claiming that the user will be *deleted*. Also the success message should not suggest that the user was deleted - because, as it turns out, the user is NOT deleted in fact.

Using WB a couple of years, this was the first time I had to delete a user group - so that might be an edge case. But anyway, the button label and the message text should be changed.

**Comment by NorHei** [comment]
The group and user settings will get a full rework as soon as they are recreated as BE tools . 

If you check out  the recent Dev version 1.2.x  you can see that settings and preferences alread are replaced by modules, pages is work in progress  and i think groups, users and media will follow in next release .  

So i don't think its a great idea to do too many changes to them now...

Btw. 1.2.x displays how many users are in a group.

**Comment by digitalbricks** [comment]
I double checked the described issue today: It was indeed what you are saying – clicking the little user icon above the user list reveals the inactive user. And in this list i found the user which should been deleted.

So you may close this ticket – but please keep the following in mind for the upcoming rework:

- say clear if a user will be *deleted* or *deactivated*
- make the button for switching from active user list to inactive user list more visible (i thought it was just a visual icon, no clickable target)

That having said, WBCE is great fork and i love using it for small projects. Thanks a lot, i appreciate your work!

**Comment by NorHei** [comment]
i agree 100% 

Just want to fix this when this part is redone anyway. This needs more that just minor enhancements.

Thx for reporting :-)
