### ISSUE TITLE
WBCE 1.2-alpha 6: Upgrade Script error

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#150]
Upgrade-script.php stops working with fatal Error in line 788 (sth. about T_STRING and "Settings")

**Comment by NorHei** [comment]
A full error message would be cool !

It helps to turn of Javascript before using the upgrade script to get a full one

**Comment by NorHei** [comment]
Parse error: syntax error, unexpected 'Settings' (T_STRING) in /var/www/web207/html/wbce12x_norbert-heimsath_de/upgrade-script.php on line 788

**Comment by NorHei** [comment]
got it

**Comment by NorHei** [comment]
5358376
