### ISSUE TITLE
Fix display errors when d&d sections

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#155]
![2016-11-15_224433](https://cloud.githubusercontent.com/assets/1433754/20325487/2a0b1d3a-ab85-11e6-9818-33cc1f3e4ab8.jpg)

**Comment by NorHei** [comment]
As i already mentioned this is a early pre version of Stefaneks page moduel , i close this as it makes no sense to discuss this before the actual module ist done.
