### ISSUE TITLE
Empty script section in head

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#156]
New frontend filter functions create 
"<script >
 
	</script>
"
directly after < head> in FE. It might be syntactical okay, but how does this look like?

**Comment by NorHei** [comment]
Right now this is the only way to deactivate the entrie .... i add  a delete option to class insert asap.

**Comment by NorHei** [comment]
9006edf. 

Fixed

**Comment by instantflorian** [comment]
Sorry to reopen, but now this block is again duplicated.

**Comment by NorHei** [comment]
was pretty tired yesterday ..

**Comment by NorHei** [comment]
15c44d1

Cops paste error ...
