### ISSUE TITLE
Prevent core modules from being unistalled

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#158]
just as reminder

**Comment by NorHei** [comment]
Schould be done by now , just add a 

$module_level="core" 

To info.php of the Module 

LEaving this open till i added  this to all modules i think that are core . 

Maybe you can help me whith a list that You think need protection.?

**Comment by instantflorian** [comment]
Well, that's quite simple i would say... Just the Preferences module, 
all the new list_ and settings_-modules,


plus
Date & Time Picker (?)
class upload
phplib
TWIG


------ Originalnachricht ------
Von: "NorHei" <notifications@github.com>
An: "WBCE/WebsiteBaker_CommunityEdition" 
<WebsiteBaker_CommunityEdition@noreply.github.com>
Cc: "instantflorian" <info@meerwinck.com>; "Author" 
<author@noreply.github.com>
Gesendet: 19.11.2016 12:45:14
Betreff: Re: [WBCE/WebsiteBaker_CommunityEdition] Prevent core modules 
from being unistalled (#158)

**Comment by NorHei** [comment]
absolutely reasonable :-)

may i ask you to add 

~~~~~~~~~~
$module_level="core";
~~~~~~~~~~~

to the info.php of those modules ?

**Comment by instantflorian** [comment]
https://github.com/WBCE/WebsiteBaker_CommunityEdition/commit/9006edfd3e63b66be80bf10ad2af8f8af0bd1b77

**Comment by NorHei** [comment]
great !
