### ISSUE TITLE
Frontend login not enabled although setting says "yes"

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#160]
On a fresh install, at "Grundeinstellungen" > "Systemeinstellungen" the setting for "Anmeldung" (Frontend login) displays "Activated", but f. ex. the "Login box" droplet shows no output.
If I switch the setting to deactivated and then again to activated, the loginbox appears.
So there seems to be sth. wrong with the initial value of this setting.

**Comment by NorHei** [comment]
388627d

Solved
