### ISSUE TITLE
Installer breaks with fatal error instead of catching missing error

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#161]
Forgot to define the database name during install and this happens:

Notice: Undefined variable: database in /.../install/save.php on line 385

Fatal error: Uncaught Error: Call to a member function SqlImport() on null in /.../install/save.php:385 Stack trace: #0 {main} thrown in /.../install/save.php on line 385

**Comment by NorHei** [comment]
hmmm ,ok wird bereinigt

**Comment by NorHei** [comment]
c89b475

Fixed

**Comment by NorHei** [comment]
btw. You must have entered some spaces , as empty Names where caught.
