### ISSUE TITLE
Remove FontAwesome from FlatTheme Package and correct the CSS link

### ISSUE THREAD

**Issue by WebDesignWorx** [WBCE/WebsiteBaker_CommunityEdition#162]
Correct this css file link:
https://github.com/WBCE/WebsiteBaker_CommunityEdition/blob/1.2.x/wbce/templates/advancedThemeWbFlat/templates/login.htt#L17

like the one here:
https://github.com/WBCE/WebsiteBaker_CommunityEdition/blob/1.2.x/wbce/templates/advancedThemeWbFlat/templates/header.htt#L22

6 of the FA Files can be then removed from here:
https://github.com/WBCE/WebsiteBaker_CommunityEdition/tree/1.2.x/wbce/templates/advancedThemeWbFlat/webfonts/fonts
(saves 6 Files amounting to 657kB less in the CMS package!)

**Comment by NorHei** [comment]
Removed

291c0e9 

Thanks a lot.
