### ISSUE TITLE
Breadcrumb broken in backend / settings

### ISSUE THREAD

**Issue by WebDesignWorx** [WBCE/WebsiteBaker_CommunityEdition#164]
In "Argos Theme" the breadcrumb link is broken:
ADMIN_URL.'/settings/index.phptitle=
(missing quotation mark before the "title=" string

In "Flat Theme" there is no breadcrumb link at all.

**Comment by NorHei** [comment]
It would help a lot if you could tell me what file and what version of WBCE

**Comment by NorHei** [comment]
Fixed the Link generation , but Flat theme  still completely kills the link , even while it is shown in html source.

**Comment by instantflorian** [comment]
change line 102 in /templates/advancedThemeWbFlat/jquery_added/jqTemplateActions.js to
// $('td.content > h4 a').click(function () {return false;});
or remove it completely
change line 48 in /templates/advancedThemeWbFlat/extern-modules-correction.css to
/*   cursor: text; */ 
or remove it completely

**Comment by NorHei** [comment]
Fixed

5fd58fc 

Thanks Florian !!!
