### ISSUE TITLE
CKEditor: WB-Link dropdown select and page_level_limit mismatch

### ISSUE THREAD

**Issue by digitalbricks** [WBCE/WebsiteBaker_CommunityEdition#165]
In a current project i am using **WBCE 1.1.6** with the bundled **CKEditor 4.4.8**. I've set a _page_level_limit_ of 2 in the WBCE advanced settings. Now, trying to place a link in the CKEditor (link type: WB-Link) the dropdown for selecting the link target page only shows pages on the first level. After changing _page_level_limit_ to 3 also the second level pages appear in the CKEditor dropdown. So it seems, CKEditor is misinterpreting the _page_level_limit_ setting of WBCE.

**For short, steps to reproduce:**

1. make sure you have some second level pages created, if not create some
2. change the _page_level_limit_ (DE: "Limit der Seitenebenen") to 2
3. try to place a link to a second level page using the CKEditor's insert-link-function, type WB-link

**Comment by NorHei** [comment]
For 1.2.x this issue is fixed here , for 1.1.x   you have to fix this  fix this manually .
As an option it should be possible to use CKE from 1.2.x  


https://github.com/WBCE/WebsiteBaker_CommunityEdition/commit/0dd38e0071aa0b3b68c039d4d7413597515b34dd
