### ISSUE TITLE
WBCE 1.1.6: Severe Error at Frontend Regstration

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#166]
Although wrong or uncomplete data is entered, a user account is created every time. So it's even possible to create user accounts with the same user names.
https://forum.wbce.org/viewtopic.php?pid=7287#p7287

Edit: Alright, it's not as bad as I presumed. It seems not to be possible to take over an existing account with more access rights. Phew!

**Comment by NorHei** [comment]
Florian you fixed it :-)
