### ISSUE TITLE
Commit 09.12: Variable uBlock?

### ISSUE THREAD

**Issue by Tenschert** [WBCE/WebsiteBaker_CommunityEdition#167]
Hello,
perhaps small bug (haven't tested) in commit ac96acd0010e83f875a6e244dcc2858b71d7a5a5 from 09.12 in file framework/functions/frontend.functions.php, function page_content():
-> page_content($uBlock);
As far as I can see, the variable wasn't declarated.
Yours, Michael

**Comment by NorHei** [comment]
I am pretty sure you are right .. killing the bug when i am at home :-)

Thanks a lot!

**Comment by NorHei** [comment]
Fixed 9727e2e
