### ISSUE TITLE
WBCE 1.2 a9: Fatal error in Show_menu2 

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#171]
No frontend output due to fatal error:

< meta name="description" content="<br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined function page_description() in /.../modules/show_menu2/include.php:16
Stack trace:
#0 /.../framework/frontend.functions.php(42): include()
#1 /.../index.php(70): require('...')
#2 /.../pages/foo.php(8): require('/var/www/web913...')
#3 {main}
  thrown in <b>/.../modules/show_menu2/include.php</b> on line <b>16</b><br />

**Comment by NorHei** [comment]
bin drann :-)

**Comment by NorHei** [comment]
811d722
