### ISSUE TITLE
Bug with I/Insert Class in the backend

### ISSUE THREAD

**Issue by WebDesignWorx** [WBCE/WebsiteBaker_CommunityEdition#172]
But with the I/Insert Class when a Warning Message in Backend appears.

See attached image:
![screenshot](https://cloud.githubusercontent.com/assets/9767034/21596509/74010daa-d13c-11e6-9059-cc1c5217415f.png)

**Comment by NorHei** [comment]
You are shure using the latest version ? It should already be fixed. 
Be filter turned on ?
![screenshot - 07 01 2017 - 02 23 19](https://cloud.githubusercontent.com/assets/1908651/21738116/a50f0004-d480-11e6-9de1-766b37fc1830.png)

**Comment by WebDesignWorx** [comment]
You may be right.
I'll install the latest revision and comment back.

**Comment by NorHei** [comment]
Just reopen , if still present
