### ISSUE TITLE
Move BE/FE template settings to system settings

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#173]
Is: default settings (Standardwerte aka Standardeinstellungen)
should be: system settings (Systemeinstellungen)

**Comment by NorHei** [comment]
Seufts ...

Bekomme bei Stefek ein immer schlechteres Gefühl ... , es wird immer 
extremer ... und extremer .... mittlerweile möchte ich eigentlich die 
Zusammenarbeit nur noch beenden :-(

Ich hatte nochmal versucht vernünftig mit Ihm zu reden , wir sind ja 
eigentlich seit ziemlich langer Zeit immer wieder im Austausch und 
irgendwie auch befreundet.  Aber irgentwie drängt sich mir da der 
Eindruck auf , das da irgendwas ganz heftig kaputt ist ....

Wie ist da so dein Eindruck  ??


Und wenn, wie werden wir ihn  Los, irgentwelche Ideen ?

Schöne Grüße
Norbert



-- 
Norbert Heimsath
Mergelstraße 25
45478 Mülheim an der Ruhr
0208 55 792

**Comment by NorHei** [comment]
The Idea to have this in default settings was to have all default settings in one place 
default Language , default timezone, default time format, default template .... 

And never having more than one screenpage of settings in a block so its possible to generate a tabbed overview for all settings .

**Comment by instantflorian** [comment]
This is still open (reasons see my PM from yesterday 08:22)

**Comment by NorHei** [comment]
You talking about renaming the settings group/module whateve ???!?

**Comment by instantflorian** [comment]
I'm talking abot moving the settings for backend and frontend template towards Systemeinstellungen since this are values which can't be changed by the users individually. The other values at Standardwerte are the values which can be configured in the profile settings, so that's why I'm thinking that the BE/FE template settings are wrong there.
But I'm getting tired discussing about this. So well, just ignore it, leave it as it is, who cares.

**Comment by NorHei** [comment]
Default Templates/themes  -> Systemeinstellungen

Default Settings keep all settings user can change .. k no problem

**Comment by NorHei** [comment]
I really had trouble understanding what to do ...
