### ISSUE TITLE
Installer throws error

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#174]
After clicking on "Install WBCE", the following error is displayed:
Error: e28: Table 'DATABASE.PREFIXmod_droplets' doesn't exist 
(DATABASE.PREFIX = real & right values)

But clicking then just again on Install WBCE => Installation works

Tested with PHP 5.5 and 7

**Comment by NorHei** [comment]
duplicate to #205
