### ISSUE TITLE
Update colorbox to 1.6.4

### ISSUE THREAD

**Issue by Colinax** [WBCE/WebsiteBaker_CommunityEdition#180]
currently we ship 1.6.0, newer version available here:
https://github.com/jackmoore/colorbox

**Comment by cwsoft** [comment]
To get the WBCE Colorbox module working, one just needs to give images the class "colorbox" - right? Tested with 1.1.11 and 1.2.x, but only got a loading icon. Can somebody test and/or provide a short howto for this feature? Tested on Windows 10, Firefox 51.0.1 and Frontend Templates WBCE (1.1.11), and wbce_vertal (1.2.x).
