### ISSUE TITLE
Update jQuery to 1.12.4

### ISSUE THREAD

**Issue by Colinax** [WBCE/WebsiteBaker_CommunityEdition#181]
The current version of the included jQuery is 1.12.0. The latest release 1.12.4 closes some bugs and brings the module up to date.

http://blog.jquery.com

**Comment by cwsoft** [comment]
Upgrading to jQuery 1.12.4 breaks the DateTime Picker layout in page manage settings section. 
Can someone else confirm this bug. Tested on Windows 10 with Firefox 51.0.1 and latest MS Edge. 
Maybe we do need to upgrade migrate.js and/or jQueryUI too to when upgrading to 1.12.4. 

If we don´t find a quick fix for this, I would recommend to stick with 1.12.0 for now.

**Comment by cwsoft** [comment]
Colinax pointed me to the missing upgrade of jQueryUI, which fixes the issues mentioned above.
Thanks for testing and reporting back 👍
