### ISSUE TITLE
Display error in Backend

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#187]
![2017-01-17_111007](https://cloud.githubusercontent.com/assets/1433754/22016196/9dadb5d0-dca5-11e6-81a9-2c196f18f2bb.jpg)

**Comment by NorHei** [comment]
Schould be fixed :-)

You killed this once , now Stefek killed it . 
Please Pull before Commiting ;-)

Fixed it 3 times now ...
