### ISSUE TITLE
Manage sections missing although activated

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#188]
![2017-01-17_111202](https://cloud.githubusercontent.com/assets/1433754/22016250/eaf2ff80-dca5-11e6-853a-772f09ba939d.jpg)

**Comment by NorHei** [comment]
Nice to hear from you Christian !
End even more nice to see you found some time !

Can you please add the submit tag to the close message ?

**Comment by cwsoft** [comment]
??? Don´t quite understand what you mean by submit tag?

**Comment by instantflorian** [comment]
when updating from WBCE 1.x the manage section link is still missing although the radio box at general setting is set to "activated". After saving the (obviuosly unchanged) settings the link is displayed again. 
That's a bit confusing.

**Comment by NorHei** [comment]
When you commit on the console , git leaves aocu a hexadecimal tagnumber in the output . If you enter this here it will link to the relevant commit.  .. The identifyer for commits , you dont need the full one , the short is enough.  But BTW. i was snowblind . 

> cwsoft added a commit that referenced this issue a day ago

If you reference it in the commit its ok too , so sorry. Its all ok.

**Comment by cwsoft** [comment]
Ah ok. Thanks for clarification.
