### ISSUE TITLE
Installer error on PHP 7.1

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#189]
Backend language select is empty
see https://forum.wbce.org/viewtopic.php?id=907

**Comment by NorHei** [comment]
Do we have a place to test ?

**Comment by cwsoft** [comment]
Fixed with commit ad88adacd9d3d62465801341c74989b7665dc418.
@Norhei: XAMPP has a PHP 7.1 package ready for installing and testing.
