### ISSUE TITLE
Security: addon file editor & Code2

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#19]
- Replace the addon file editor in the package with cwsoft's re-worked module, as the "old" one throws multiple warnings:

> Warning: mysql_real_escape_string(): Access denied for user ''@'localhost' (using password: NO) in 
> /var/www/.../modules/addon-file-editor/code/functions.php on line 515

> Warning: mysql_real_escape_string(): A link to the server could not be established in /var/www
> /.../modules/addon-file-editor/code/functions.php on line 515

- or do not ship any addon file editor due to security reasons => remove from package?

**Comment by cwsoft** [comment]
Due to security concerns, it is proposed to remove the modules "addon-file-editor" and "Code2" from the WBCE core package and offer those as external downloads. I would vote for this step too to keep the WBCE core secure, small and maintainable.

**Comment by webbird** [comment]
Removed
