### ISSUE TITLE
WBCE 1.2 new Installation fails due to OPF too 

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#190]
Notice: Undefined variable: imports in /.../modules/topics/install.php on line 304

Warning: opf_is_registered(): Filter not registred in /.../modules/outputfilter_dashboard/functions.php on line 673

Warning: opf_is_registered(): Filter not registred in /.../modules/outputfilter_dashboard/functions.php on line 673

Fatal error: Uncaught Error: Call to undefined function opf_is_registed() in /.../modules/mod_opf_short_url/install.php:38 Stack trace: #0 /.../modules/outputfilter_dashboard/install.php(115): require() #1 /.../framework/functions/functions.php(1036): require('/var/www/web913...') #2 /.../install/save.php(464): load_module('/var/www/web913...', true) #3 {main} thrown in /.../modules/mod_opf_short_url/install.php on line 38

**Comment by instantflorian** [comment]
After deleting all that OPF stuff installation still fails

 Parse error: syntax error, unexpected 'if' (T_IF) in /.../modules/droplets/install.php on line 42

**Comment by instantflorian** [comment]
No, it's pointless. 
I'm giving up at the moment. :(

Notice: Undefined variable: imports in /.../modules/topics/install.php on line 304

Warning: opf_is_registered(): Filter not registred in /.../modules/outputfilter_dashboard/functions.php on line 673

Warning: opf_is_registered(): Filter not registred in /.../modules/outputfilter_dashboard/functions.php on line 673

Warning: Cannot modify header information - headers already sent by (output started at /.../modules/topics/install.php:304) in /.../install/helper_functions.php on line 30

**Comment by instantflorian** [comment]
BTW, please have also a look at WB classic forum. Don't get me wrong, this OPF stuff might be useful in some cases, but at WB classic the filters cause lots and lots of problems. We certainly HAVE to avoid to make the same mistakes.

**Comment by NorHei** [comment]
Testing Upgrade right now , so tessting installl next  step. 

1. The filters are still the same copied from WBCE :-)

2. The Fatal errors where simple typos "undefined function opf_is_registed()" should be opf_is_registered

2. the topics bug , seemst to be fixed for me there is a 
~~~~~~~~~
if (!isset($imports)) $imports=array();
~~~~~~~~~~
In the topics install.php 
Did you possibly not overwrite topics ?
Changing this anyway to the more elegant var definition on function start.  

3. Warning: Cannot modify header information - headers already sent by (output started at /.../modules/topics/install.php:304) in /.../install/helper_functions.php on line 30

This is topics again preventing redirect.  

4. The warnings where for Debug  , but they need to be removed , cause install would fail from them too.  

On it , nothing spectacular just some minor bugs in New modules.

**Comment by NorHei** [comment]
Ok, topics fixed version not uploaded ... now it is . 
8e5b043. 

Fatal Errors are fixed  too already . 

Warnings should be deactivated by Mrbaseman already.
... oops ... ok deactivated em  

Should all be fixed ... reopen if any more problems 

Still double shifts and here we go :-)
