### ISSUE TITLE
Buttons of Droplets 2.1 module look weird

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#196]
![2017-01-18_091359](https://cloud.githubusercontent.com/assets/1433754/22056203/3c8e5b00-dd5f-11e6-9803-ce17f32a2f5a.jpg)

**Comment by NorHei** [comment]
I guess i remove stefeks changes to templates completely ....

**Comment by instantflorian** [comment]
good idea.

**Comment by instantflorian** [comment]
Now they look weird another way -.-

![2017-01-21_124433](https://cloud.githubusercontent.com/assets/1433754/22174160/8591549a-dfd7-11e6-870b-8d42706a7697.jpg)

**Comment by NorHei** [comment]
edd5352

Fixed
