### ISSUE TITLE
Display error on settings modules

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#197]
![2017-01-18_092158](https://cloud.githubusercontent.com/assets/1433754/22056290/b2779c1e-dd5f-11e6-9eff-7f1cbd89edbc.jpg)

**Comment by instantflorian** [comment]
Same on Systemeinstellungen

**Comment by NorHei** [comment]
Looked for this a few times .. i cannot find the reason for this , do you have any idea what is changed in the HTML , if we find this change , ist easy to hunt it down .

**Comment by instantflorian** [comment]
appears only in Chrome, not in FF.
Seams to be this one:
http://stackoverflow.com/questions/9691771/why-is-65279-appearing-in-my-html

**Comment by NorHei** [comment]
Whoa ... giving it a try when home .. cool !!!

**Comment by instantflorian** [comment]
fix: add in /templates/advancedThemeWbFlat after line 599:
top:0;

**Comment by NorHei** [comment]
Sorry , what file ?

**Comment by instantflorian** [comment]
oops... /templates/advancedThemeWbFlat/theme.css

**Comment by NorHei** [comment]
Is it done whith the theme.css you send me ?
