### ISSUE TITLE
Frontend login on registered page does not work

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#198]
Set page dto Sichtbarkeit: registriert
Log off from CMS 
Try to access page
Fill in login form => nothing happens, just the page is reloaded
![2017-01-18_093355](https://cloud.githubusercontent.com/assets/1433754/22056641/5062eee6-dd61-11e6-8505-91c0c5ab79f6.jpg)

**Comment by NorHei** [comment]
Need a test enviroment ...

**Comment by cwsoft** [comment]
Password and Username are provided in obfuscated POST input fields (e.g. username_ojlxcskt). As the if block in [class.login.php](https://github.com/WBCE/WebsiteBaker_CommunityEdition/blob/1.2.x/wbce/framework/classes/class.login.php#L49-L50) is always TRUE, the elseif block below is never executed and hence the POST password and username are always empty.

As the login class was completely rewritten by Norhei, I won´t touch the code to avoid possible side effects. Changing the login class as shown below should solve the issue - but may have unwanted side effects I may have overlooked.

```
class login extends admin
{
    public $username_fieldname = 'username';
    public $password_fieldname = 'password';

    public function __construct($config_array)
    {
        // Get language vars
        global $MESSAGE, $database;

        // use admin class constructor
        parent::__construct();

        // Get configuration values, and set them as class vars
        while (list($key, $value) = each($config_array)) {
            $this->{(strtolower($key))} = $value;
        }

        // set Redirect url ..
        if (!isset($this->redirect_url)) {$this->redirect_url = '';}

        // check if login fieldnames were submitted via POST request (e.g. username_ojlxcskt)
        if (($this->get_post('username_fieldname') != '') AND ($this->get_post('password_fieldname') != '')) {
            $this->username_fieldname = $this->get_post('username_fieldname');
            $this->password_fieldname = $this->get_post('password_fieldname');
        }

        // fetch username and Password
        $this->username = $this->get_post($this->username_fieldname);
        $this->password = $this->get_post($this->password_fieldname);

        // If the url is blank, set it to the default url
        // END OF CHANGES
```

Will leave it up for Norhei to provide an update for this.

**Comment by NorHei** [comment]
Get it going  :-) I would try the same on first step .

**Comment by instantflorian** [comment]
Seems to be fixed

**Comment by cwsoft** [comment]
Commited my proposed changes to the login class.
