### ISSUE TITLE
Change default frontend templates

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#199]
Replace "WBCE" and "Simple Responsive" with "Hortal and "Vertal"
Set default frontend template in install script to one of them (but not during upgrade of course)

**Comment by NorHei** [comment]
Where to download ?
What is the better one for use as default ?

**Comment by instantflorian** [comment]
http://wbce.at/tpls/template-hortal.html
http://wbce.at/tpls/template-vertal.html
Which one? Difficult question. I would say vertal, it's easier to get it running out of the box

**Comment by NorHei** [comment]
Ok !!

**Comment by NorHei** [comment]
b7fb81f

**Comment by instantflorian** [comment]
Sorry to reopen, but afaik the new templates were not ready yet - for example does the permanent saving of the changed fe colors already work?

**Comment by NorHei** [comment]
I have no idea ? Maybe ask chio.

**Comment by NorHei** [comment]
Do not fear to reopen :-)

**Comment by NorHei** [comment]
Hi , whats whith this now ?

**Comment by instantflorian** [comment]
The old templates still need top be deleted and I don't know how far the frontend color switcher is finalized.

**Comment by NorHei** [comment]
Are there any newer versions of those templates ?

**Comment by instantflorian** [comment]
apparently not, the download on wbce.at is not available any more. So I 
guess we should/have to stick to the current ones. If the color chooser 
does not work, we should eep it in mind for a next version but cancel it 
for the moment, it's more important to have a shiny template anyway than 
spending much more time for minor details.

**Comment by instantflorian** [comment]
update:
https://forum.wbce.org/viewtopic.php?pid=9257#p9257

**Comment by instantflorian** [comment]
The old templates still need top be deleted

**Comment by cwsoft** [comment]
@instantflorian: They are deleted from the [WBCE 1.2.x branch](https://github.com/WBCE/WebsiteBaker_CommunityEdition/tree/1.2.x/wbce/templates), as this was labelled with 1.2.0 milestone.

**Comment by instantflorian** [comment]
I'm sorry, my mistake. I've looked in the wrong directory.
