### ISSUE TITLE
Unable to install WB modules

### ISSUE THREAD

**Issue by webbird** [WBCE/WebsiteBaker_CommunityEdition#20]
Since changing the WBCE version to 1.0.0, some modules fail to install (OneForAll, Bakery), other may throw errors (mpform).

**Comment by cwsoft** [comment]
I have only tested WB Modules for WB 2.8.3. Haven´t tested older WB versions or it´s forks (Lepton, BC). Thanks for reporting.

**Comment by cwsoft** [comment]
This bug should be solved with Commit [dc1d3eef9]. Please test and provide feedback if we can solve this issue.
