### ISSUE TITLE
Droplets & WBLink button freeze CKEditor

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#200]
![2017-01-18_095416](https://cloud.githubusercontent.com/assets/1433754/22057542/6c1900ae-dd65-11e6-8c5a-7de566af1841.jpg)
issue with the moduleversion 4.5.11, rollback to 4.5.5 => buttons work as expected

**Comment by NorHei** [comment]
Can You post this to the Forum , i just used the CKE posted there !!

I leave it in , so he can test it , but wait till i hunted the installer bugs

**Comment by NorHei** [comment]
happens on both argos and Flatt ..

**Comment by NorHei** [comment]
Fixed it !

e9c4415
