### ISSUE TITLE
Wrong language code

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#202]
CA =! Canada, CA == Catalan 
The flag symbol seems to be the right one 
![2017-01-18_213106](https://cloud.githubusercontent.com/assets/1433754/22081846/8d558728-ddc5-11e6-9fea-c0992762d6e2.jpg)

**Comment by NorHei** [comment]
Installer ?

**Comment by instantflorian** [comment]
Nee, Backend

**Comment by NorHei** [comment]
Preferences ?  Where exactly ?

BTW i see no flags in Chrome

**Comment by instantflorian** [comment]
http://www.wbce.org/2017-01-18_212655.jpg

**Comment by NorHei** [comment]
Language Code should be fixed , On upgrade reloading of Languages was deactivated . 

Language file is fixed too , my new installlation shows right language. 



![screenshot](https://cloud.githubusercontent.com/assets/1908651/22139174/deac7972-dee4-11e6-9e8f-00cb5ca2c8bf.png)


Still there is an issue about this , as the flags simply won't show .
They are present in Source , but the won't show.  

As this is an CSS issue i am asking you for help !

I basically used the same Template  that was used bevore. 

Template is in module/preferences/templates/   
There are no overrides in the main Templates

**Comment by instantflorian** [comment]
Theres nothing one can do. The flags just show up only in Firefox, that 
has always been like this.
http://stackoverflow.com/questions/25200217/how-to-display-an-image-in-the-options-of-select-box-in-chrome

**Comment by NorHei** [comment]
Ah ok , then i close it
