### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#205]
Error: e27a: /topics : Table '{TABLE}.{PREFIX}mod_droplets' doesn't exist

{TABLE}, {PREFIX} = correct values

Well, of course it does not exist, I'm trying to install a new instance... -.-

**Comment by NorHei** [comment]
I always thought this error was dorplets .. thanks to new debug , we now know thats Topics .. Trying to install a droplet bevore Droplets are installed ... :-)
We have this as a duplicate somewhere here :-)

**Comment by NorHei** [comment]
Depending on the order of the files in the filesystem , this error may appear , or may not . 
On second run the droplets tables are installed , and topics runs through. :-)

**Comment by NorHei** [comment]
Should be fixed now , but cannot test , as my filesystem seems to do some kind of sorting , so error never appears.  

f0d6135

**Comment by instantflorian** [comment]
Sorry, this is the reason, but that is no final solution. It is inacceptable that the installation fails randomly. It is not user friendly and will lead to distrust and irritation.

-------- Ursprüngliche Nachricht --------
Von: NorHei <notifications@github.com> 
Datum:21.01.2017  11:12  (GMT+01:00) 
An: WBCE/WebsiteBaker_CommunityEdition <WebsiteBaker_CommunityEdition@noreply.github.com> 
Cc: instantflorian <info@meerwinck.com>,Author <author@noreply.github.com> 
Betreff: Re: [WBCE/WebsiteBaker_CommunityEdition] Installation fails (#205) 

Depending on the order of the files in the filesystem , this error may appear , or may not .
On second run the droplets tables are installed , and topics runs through. :-)

**Comment by NorHei** [comment]
f0d6135

Droplets is simply installed first now  :-)

**Comment by NorHei** [comment]
```````
// As some Module need to install Droplets we need Dropletss in next step 
    load_module( $dirs['modules'] . 'droplets', true);
    if ($admin->error != '') {
        set_error(d("e26c: /droplets : ").$admin->error,"",true);
    }
    if ($database->is_error()) {
        set_error(d("e26d: /droplets : ").$database->get_error(),"",true);
    }

```````

**Comment by NorHei** [comment]
7445f51 

Ups, had a copy paste error in installer.
