### ISSUE TITLE
Frontend login form looks disgusting

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#207]
![2017-01-21_124130](https://cloud.githubusercontent.com/assets/1433754/22174147/16336714-dfd7-11e6-9e90-500cc12e35c8.jpg)
(...and still does not work)

**Comment by NorHei** [comment]
Again , you have a place for me to test ?

**Comment by cwsoft** [comment]
@instantflorian: Can you take care of styling the frontend login so it looks great again :-)
I am no designer, so I can´t really help out on this issue.

**Comment by instantflorian** [comment]
I will do when it works again.
Thought there was a plan to move this to a module too btw?

**Comment by cwsoft** [comment]
Ok, thanks for clarification.

**Comment by instantflorian** [comment]
Fixed
https://github.com/WBCE/WebsiteBaker_CommunityEdition/commit/8c4f8f5f4d432d9842c093fa94f9d5e7b8f6e7b2
