### ISSUE TITLE
Remove Button Admintools from Maintainancemodeswitcher at Grundeinstellungen

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#208]
![2017-01-21_130143](https://cloud.githubusercontent.com/assets/1433754/22174249/e7b69e12-dfd9-11e6-99a1-1850a1a2c980.jpg)

**Comment by NorHei** [comment]
Same for settings . 
You can help me if you like , just hop in the template folder of the module , and remove  it or comment it out.  . 
Its plain php + hml 

What about a second breadcrumb below ?

**Comment by instantflorian** [comment]
I'm afraid of using the Git client, havent used it for weeks and maybe I'll overwrite all changes since then.

**Comment by NorHei** [comment]
4400f0e

Please reopen if i missed some
