### ISSUE TITLE
Duplicate Twig in the WBCE package

### ISSUE THREAD

**Issue by WebDesignWorx** [WBCE/WebsiteBaker_CommunityEdition#21]
After I made [this comment](https://github.com/WBCE/WebsiteBaker_CommunityEdition/issues/2#issuecomment-124214334), Twig was added to the include folder.

This makes the __TwigTE__ directories in `modules/addon_monitor` and `modules/wbSeoTool` obsolete.
I think you can just exclude both without any problems. (I didn't test it though.)

It will decrease the upload time considerably.

Kind regards, 
Stefek

**Comment by webbird** [comment]
Thanks for the hint!
