### ISSUE TITLE
OPF Dashboard throws warning

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#211]
Warning: opf_filter_get_data(): global Array not defined in /.../modules/outputfilter_dashboard/functions_outputfilter.php on line 1359

**Comment by NorHei** [comment]
Where and when this occurs??

**Comment by instantflorian** [comment]
Forget it, can't reproduce

**Comment by instantflorian** [comment]
Doch, jetzt ja: wenn der Dropletfilter deaktiviert wird
![Uploading 2017-01-22_094949.jpg…]()

**Comment by NorHei** [comment]
Handed this to Martin ..

**Comment by NorHei** [comment]
Should be fixed already 
Please validate

**Comment by mrbaseman** [comment]
FYI: I have just pushed version 1.5.1 to https://github.com/WebsiteBaker-modules/outpufilter_dashboard - this is the one we have in the WBCE 1.2 branch
