### ISSUE TITLE
Avoid module installation error due to php tags in comments

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#214]
Due to "<?php" as text (not code which should be executed) in the info.php of some modules, e.g. Bakery, installation of those modukes fails.
To avoid this, change  /admin/modules/install.php, line 119:
from $exec=preg_replace("/^.*\<\?(php)?/uis","", $exec);
to $exec = preg_replace("/^.*\<\?(php)?/ui", "", trim($exec));

(thanks to freesbee)

**Comment by NorHei** [comment]
69ae9e2
