### ISSUE TITLE
Droplets 1.75, 2.0, 2.10: Module throws fatal error if syntax error in Droplet 

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#216]
Step 1: edit or create any droplet and forget a ' or a ) or sth. that way
Step 2: Save
Instead of the list of droplets, you see only
Parse error: syntax error, unexpected end of file in /.../modules/droplets/functions.inc.php(247) : eval()'d code on line 17

**Comment by instantflorian** [comment]
Turns out, it's a PHP7 issue:
"As of PHP 7, if there is a parse error in the evaluated code, eval() throws a ParseError exception. Before PHP 7, in this case eval() returned FALSE and execution of the following code continued normally."
http://php.net/manual/en/function.eval.php

=> Workaround: comment out the line beneath check_syntax:
    return @eval('return true;' . $code);

But how could this be fixed the right way?

**Comment by NorHei** [comment]
http://stackoverflow.com/questions/10085284/how-to-handle-parse-error-for-eval-function-in-php

Maybe inform Webbird on this .

**Comment by NorHei** [comment]
Where can i test ? Have no php 7 available.

**Comment by instantflorian** [comment]
As I wrote by mail feel free to install test instances on the webspace I mentioned. There you can switch between PHP 5.x and 7.x simply by using the .htaccess command.

We really HAVE to find a solution for this problem - that a forgotten bracket or quote kills the backend is inacceptable. Please priorize a this issue as the highest level.

**Comment by NorHei** [comment]
Sorry i have lots of trouble whith m internet provider right now ... connection constantly dropping , i never get a full upload ready  atm

**Comment by NorHei** [comment]
Ok, the error is fixed . Still the check results are not displayed e.g. drops do not turn red. 
But this is going wrong whith and whithout php7(whith and whithout the fixed function), so its basically another issue.  
 Fixing this later as my time is out.

**Comment by cwsoft** [comment]
Updated Droplets in WBCE 1.2.x Branch to v2.1.1. This version should fix the reported bug and works with PHP5 and PHP7/7.1.

**Comment by instantflorian** [comment]
Do we have a chance to get this version running under WBCE 1.1.x too? Currently this fails with

Fatal error: 
Uncaught Error: Call to a member function numRows() on null in /.../modules/droplets/functions.inc.php:452 
Stack trace: #0 /.../modules/droplets/tool.php(205): wbce_list_droplets() 
#1 /.../admin/admintools/tool.php(77): require('...') 
#2 {main} thrown in /.../modules/droplets/functions.inc.php on line 452

**Comment by cwsoft** [comment]
@Florian. We shouldn´t mix issues for different milestones. 

I would recommend to set this issue closed again and just create a new commit and label it 1.1.x. Honestly I have no glue what versions of some modules (e.g. Topics, Droplets etc.) are used in the WBCE 1.1.x and 1.2.x branches.

**Comment by instantflorian** [comment]
accepted
