### ISSUE TITLE
openssl_random_pseudo_bytes() in framework\classes\randomgen.php 

### ISSUE THREAD

**Issue by Tenschert** [WBCE/WebsiteBaker_CommunityEdition#218]
Hello,

the function openssl_random_pseudo_bytes() in framework\classes\randomgen.php doesn't seem to be part of many webservers. 
Here XAMPP, PHP 5.6.8 on Win 10:
> "Fatal error: Call to undefined function openssl_random_pseudo_bytes() in C:\CMS_Develop\XAMPP\portable_568\htdocs\www\WBCE12\framework\classes\randomgen.php on line 87"

**Comment by NorHei** [comment]
Damm ... and thanks !!

**Comment by NorHei** [comment]
I guess its a  Windows isssue as this lib is on every Unix server that uses ssl/ssh  in some way. (https/ssh/sftp... ) . Still this is an issue as we don't want to drop Win support.

**Comment by NorHei** [comment]
Fixed in  64f8cc9

Can you please verify , as i have no system whithout openssl or whith Windows :-) 

Please reopen if problem still occurs. 
Thanks for report!

**Comment by Tenschert** [comment]
Thanks very much - I tested it under XAMPP / Win10, now there's no error anymore.
