### ISSUE TITLE
New htaccess.txt is too complicated

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#220]
Do we really need this monster-htaccess? The .htaccess of WBCE 1.1 has only a bunch of lines and IT WORKS out of the box when renamed. The new one does not, there are duplicated lines and even removing the # in front of them make not the htaccess work properly, i.e. to force www in url.

So I guess we should roll back to the htaccess from 1.1.

**Comment by cwsoft** [comment]
Proposal: ship two htaccess files. 
htaccess_light.txt: bare minimum to get short.php running nothing else
htaccess_full.txt: all the fancy stuff you can do with htaccess incl. documentation.ä

**Comment by instantflorian** [comment]
+1

**Comment by NorHei** [comment]
Maybe i schould habe a word whith Ruud about this ?

As i never used this module ..

**Comment by cwsoft** [comment]
@NorHei: Yes, please contact Ruud so we can move on with this issue.

**Comment by cwsoft** [comment]
Anbei mal eine leicht modifizierte .htaccess. Basiert auf WBCE 1.1.11 und wurde um ein paar Kommentare und Ergänzung für google_sitemap.php angereichert.
[htaccess_light.txt](https://github.com/WBCE/WebsiteBaker_CommunityEdition/files/836457/htaccess_light.txt)
