### ISSUE TITLE
Notices in argos_theme_reloaded when viewing page tree

### ISSUE THREAD

**Issue by cwsoft** [WBCE/WebsiteBaker_CommunityEdition#223]
Some notices are shown in argos_theme_reloaded when viewing the page tree:

Visibility (Pages): $fa) : ?>    
Notice: Undefined variable: icon in ..\templates\argos_theme_reloaded\patch\page_tree.php on line 383
Notice: Undefined index: in ..\templates\argos_theme_reloaded\patch\page_tree.php on line 383

@BerndJM: Can you please take a look on this notices?

**Comment by BerndJM** [comment]
Puh ... why I can't see this error on my local system with ErrorLevel E_EVERYTHING ?
Maybe the PHP version? using 5.6 here ...

**Comment by cwsoft** [comment]
Ok. With your latest changes included, I get the following errors:

Notice: Undefined variable: statusMap in ..\templates\argos_theme_reloaded\patch\page_tree.php on line 381

Warning: Invalid argument supplied for foreach() in ..\templates\argos_theme_reloaded\patch\page_tree.php on line 381

To reproduce the error:
a) make a clean installation with your latest 1.2.x tree
b) login and change backend to Argos reloaded
c) go to the page view (no page yet created) and see the error

Tested on PHP 5.6, 7.0 and 7.1 (XAMPP, Windows 10).

**Comment by BerndJM** [comment]
Thanks for testing and reporting,
just found the issue, give me some minutes to fix

**Comment by cwsoft** [comment]
Cool. Crossing fingers right :-)

**Comment by BerndJM** [comment]
have I make a new pull request or can you fetch the changes otherwise?

**Comment by cwsoft** [comment]
👍
