### ISSUE TITLE
Module installation fails if folder unzip exists in temp?

### ISSUE THREAD

**Issue by BerndJM** [WBCE/WebsiteBaker_CommunityEdition#227]
Maybe only a local problem with filepermissions?
Couldn't install any module in my "playground". 
Investigating this I found a /temp/unzip folder  - probably left over from a former failed installation?(content was: "topics_rss_statistic.php"). 
As soon as I deleted the /unzip folder, installation works again.

**Comment by cwsoft** [comment]
Couldn't find a folder called temp/unzip in the Github Master and 1.2.x branches. Those files are created by the Topics module during installation/upgrade process. Topics tries to import a Droplet into the DB by importing Droplets functions file to call the registration process. 

This in one of the issues an upgrade from older WBCE version fails.

**Comment by BerndJM** [comment]
As far as I see: the /unzip is temporary generated during module-installation and deleted afterwards.
If the /unzip folder isn't deleted (for whatever reason) a next installation fails.
Ok, as I said before: Maybe only a local problem with filepermissions ...

**Comment by cwsoft** [comment]
Had a similar issue yesterday with Topics upgrade, which tries to extract a zipped Droplet to temp/unzip. Folder had no writepermissions for whatever reason (Windows 10, XAMPP). So there might be Addons (upgrade/install) which do not clean up properly, causing the issues you mentioned.
