### ISSUE TITLE
Update CKE to newest version

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#229]
(just as reminder)
Thanks to colinax we'll have a brand new CKE 4.6.2 which should be of course included into the version 1.2

**Comment by Colinax** [comment]
Thanks for the reminder, there are still smaller bugs available. But it should be finished by Tuesday at the latest.

**Comment by NorHei** [comment]
Can you generate a pull request when its done so far ?

**Comment by NorHei** [comment]
Added the pull
