### ISSUE TITLE
Remove unnecessary BE themes

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#232]
Now there is a "argos theme", "reloaded argos theme", and "default theme based on argos theme". 
That is ridiculous!
 We should stick to the reloaded argos theme and remove the other "argosses" .

**Comment by cwsoft** [comment]
We should also reconsider the concept of the default theme. Guess it is only usefull during upgrade.

**Comment by instantflorian** [comment]
There's still "Default theme based on argos theme". Please remove.
![toomuchtemplates](https://cloud.githubusercontent.com/assets/1433754/24839521/5f90fc7e-1d5c-11e7-8856-7c6f2cb1dc04.jpg)

**Comment by NorHei** [comment]
040dc48
