### ISSUE TITLE
Should short.php be removed with WBCE 1.2.0?

### ISSUE THREAD

**Issue by cwsoft** [WBCE/WebsiteBaker_CommunityEdition#234]
I would vote for removing short.php and the htaccess.txt file with WBCE 1.2.0 due to the following reasons:

- it doesn´t work in subfolders or in subdomains (e.g. VirtualHosts) out of the box
- needs to be adapted in case media/, admin/, pages/ folder is renamed
- may interfeer with other .htaccess settings (e.g. error document, rewrite rules, PHP handlers etc.)
- requires knowledge of Apache .htaccess in many cases (target WBCE audience won´t have)
- simple error in the .htaccess file may result in a Error 500 page easily
- too many possible options not included (e.g. with or without www, with or without trailing / etc.)
- it only works on Apache servers, but not on Windows IIS

So I would remove short.php and maybe the [[Shorturl]] Droplet as well. If needed, one can install it from the Dev4Me website. 

Any comments, votes on that??

**Comment by Colinax** [comment]
+1 for removal

**Comment by instantflorian** [comment]
+1 from me too (although it's a pity, but better no solution than this)

**Comment by NorHei** [comment]
+1 For me too 

... We dont need the Droplet any more , its a filter you can turn on off. 
My personal Plan was keeping it in 1.2.x  And move this to an Installable Module  on 1.3.x
Removing it from Core in 2.0.  

As i simply don't wanted to break existing pages that only upgrade from 1.1 

@cwsoft 
Quite a lot of those Problems occure whith any URL rewriting CMS ;-)
