### ISSUE TITLE
Update included external modules

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#238]
just as reminder:
include current versions of Sitemap, MiniForm and W.... Visitor Statistics (we should fork this module due to its current naming btw).

**Comment by Colinax** [comment]
We should also update Font-Awesome, Twig and PclZip. For Twig and PclZip are php7 updates available.

**Comment by Colinax** [comment]
The updates of these modules are in the Pull request, except Visitor Statistics and PclZip
