### ISSUE TITLE
Undo renamig of "Einstellungen"

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#239]
I would prefer the naming "Grundeinstellungen", it's communicated everywhere.

**Comment by cwsoft** [comment]
I would prefer to keep "Einstellungen" for the left backend menu and the top breadcrump settings as this is just the entry point for lot of settings (default, extended, server, email ...). However I would rename Standartwerte to Grund-Einstellungen, as it makes more sense to me? For clarification, see screenshot.

<img width="910" alt="settings" src="https://cloud.githubusercontent.com/assets/1426817/24816871/c9e0649e-1bda-11e7-8d5d-9984c4012709.PNG">

**Comment by instantflorian** [comment]
I confess that "Einstellungen" is shorter and looks better. But this naming was introduced with 1.x, and for my opinion it's a major change which should not be done until 2.x when more basic things will change. But I won't argue about this, compared with other issues this is rather ridiculous too. So if your heart blood hangs to this - well, there you go.
Standardwerte at this place shoud stay, for these are the default values which every backend user will get until he changes it in his profile settings.

**Comment by cwsoft** [comment]
By splitting the old settings into several smaller blocks the naming "Einstellungen" just makes more sense to me than "Grundeinstellungen". It´s up to you as project lead. If you want to have it changed back, we will do.

**Comment by instantflorian** [comment]
The term "Grundeinstellungen" is found about 100 times in the WBCE support forum, so this renaming might confuse the users ("You wrote to change it at Grundeinstellungen, but I can't find this menu item"... etc) - so this is the reason I'm hesitating over this name change...
