### ISSUE TITLE
Do not set page language=activated during update

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#240]
This leads to "Website under construction" in many cases. The value for "Seitensprache" (Page Languag) must not be changed during update.

**Comment by NorHei** [comment]
As far as i remember we decided to have this on by default , hey we found an unwanted Sideffect ;-)

Hmm checking the upgrade script , its not changing anything ... 

if (!defined('WB_PAGE_LANGUAGES')) Settings::Set ("wb_page_languages", PAGE_LANGUAGES);

**Comment by NorHei** [comment]
nothing in module settings_general 
Only thing i can find is that the Default Value for Settings general defaults to true. 
I can set that to false .

**Comment by instantflorian** [comment]
Strange. I think that setting this to false is better then.

**Comment by NorHei** [comment]
Already done , reopen if it comes up again
