### ISSUE TITLE
Review settings at Einstellungen and Admintools

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#242]
Still confusing:

Duplicates:
At (Grund-)Einstellungen (G)  and Admin Tools (A) exist settings for

- Output Filter (G) ~~~ OutputFilter - Dashboard (A)
- Wartungsmodus Umschalter (G) ~~~ Maintainance Mode Switcher (A)
-  Sicherheits Einstellungen (G) ~~~ Secure Form Switcher (A)

Not a tool, should be at settings:

- Captcha and Advanced-Spam-Protection (ASP) Control (A => G)
- Javascript Admin (A => G)

**Comment by instantflorian** [comment]
To make it clearer...
## Remove at Admin Tools:
- Secure Form Switcher (**duplicate** to Sicherheitseinstellungen)
- Captcha and Advanced-Spam-Protection (ASP) Control: it's a setting, so it should be **moved** to Grundeinstellungen
- Javascript Admin: it's a setting, so it should be **moved** to Grundeinstellungen
- Maintainance Mode Switcher (after updates from 1.1.x **duplicate** to the Wartungsmodus setting)

##Remove at Grundeinstellungen:
- Output filter (actually I'm not sure about this, whether its more a tool or more a setting. Due to its complexity I think it's better to have this at Admintools)

So we have at Grundeinstellungen
- Standard Einstellungen 
- System-Einstellungen 
- Mail-Einstellungen 
- Such-Einstellungen 
- Sicherheits Einstellungen
- SEO/Metadaten-Einstellungen
- Server-Einstellungen 
- JavaScript Admin
- Captcha and Advanced-Spam-Protection (ASP)
- Wartungsmodus

and at Admin-Tools by default
- AddonMonitor
- Backup
- Droplets
- Output Filter Dashboard
- Page Cloner
- SEO Tool
- User search
- Visitor statistics

**Comment by NorHei** [comment]
Done so far , but if i remeber it correct you wanted some Settings moved around , please add the list here too.

**Comment by instantflorian** [comment]
Thanks. Looks good so far. I just committed some changes to avoid too long titles/descriptions.

**Comment by NorHei** [comment]
Always good :-)

**Comment by instantflorian** [comment]
Just to mention: will this be monitored during upgrade process too, eg. foes the upgrade script remove the not-wanted settings/admin tools?

**Comment by NorHei** [comment]
Yes  it does , redundant Modules removed in Upgrade Script
