### ISSUE TITLE
SSL/TLS support

### ISSUE THREAD

**Issue by DJCrashdummy** [WBCE/WebsiteBaker_CommunityEdition#243]
is there any way to get WBCE working with SSL/TLS enabled?

i wanted to use WBCE (because i tried WebsiteBaker quite a while ago and liked it) but now i had to find out, that both frontend- and backend-themes are messed up or completely broken with SSL/TLS.
i'm really surprised because nowadays (in the time of free certificates) a SSL/TLS-no-go is pretty uncommon, and logging in without it, dealing with personal data and so on is sadly a deal breaker. :-(

if there is no way to get it working yet, please fix this if anyhow possible; and or at least is there anything you can tell me about it, a progress, pros/cons or anything else since i found nothing about it in your forum.

anyhow thanks for your time and work!

**Comment by mrbaseman** [comment]
Just a remark: I had the problem with WB, too, and found out that it's important to define WB_URL with https://. To my knowledge there is no logic (yet) inside of WB or WBCE that detects if you are viewing the page through https or not and accordingly modifies the menu links (this would be a nice use case for an output filter)

**Comment by mrbaseman** [comment]
Let me correct myself, the sys rel output filter should do the job of tuning the menu links etc. in a way that both http and https work 

Prerequisite for all that is that WB_URL is used consistently in the templates

**Comment by DJCrashdummy** [comment]
thanks for the hint with the **_WB_URL_** in the **config.php**... it looks good for now! - for example also [this warning](https://support.mozilla.org/t5/Protect-your-privacy/Insecure-password-warning-in-Firefox/ta-p/27861) is gone... so it may work with links and so on.

i just wonder why there is nothing to find about this not even a note anywhere...?!? :-/

**Comment by mrbaseman** [comment]
well, strictly spoken, enabling ssl/tls is not something you configure in WBCE. It's a configuration task concerning the web server in which WBCE is running. The only point of contact is the "s" in https of the WB_URL. I think that's the reasoning behind this. But, you are right, we should put a hint about it in the installer, or at least in its documentation

**Comment by DJCrashdummy** [comment]
for sure enabling ssl/tls belongs to your server, but i installed more than 10 CMS on the same server with ssl/tls enabled and forced... and non except WBCE (i can't tell for Websitebaker) had problems working with it.
after the mozilla-warning for the password and i was sure the GUI was screwed up, i looked around and just found [this hints](http://help.wbce.org/pages/de/installation/systemvoraussetzungen.php) for configuration and also anywhere else no word about ssl/tls...

yes, a hint would be useful for sure in the documentation (also that a switch to ssl/tls is obviously easily possible)! - and if not detected automatically, a small note about httpS in the installer will also be nice. ;-)

thank you for your hints, your time and the productive conversation!

**Comment by instantflorian** [comment]
https://forum.wbce.org/viewtopic.php?pid=10605#p10605

**Comment by DJCrashdummy** [comment]
also the system requirements in [english](http://help.wbce.org/pages/en/installation/system-requirements.php?lang=EN) and [german](http://help.wbce.org/pages/de/installation/systemvoraussetzungen.php?lang=DE) got an update! :-)

@instantflorian: the english one suffer a typo (_thhps_) and also a link to the forum-post (as it is bilingual), like in the german one would make sense.

**Comment by instantflorian** [comment]
Thank you for your feedback, I corrected the typo and added the link to 
the forum.
