### ISSUE TITLE
Wrong class in show_menu2

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#245]
If a page has only hidden child pages, show_menu2 generates the class menu_expand nevertheless (what is actually wrong, because there's nothing to expand).
Reported by kleo
https://forum.wbce.org/viewtopic.php?pid=10701#p10701

**Comment by NorHei** [comment]
ahh that reminds me of chio mentioning this a while ago

**Comment by NorHei** [comment]
thi is a very old wb bug :-)
