### ISSUE TITLE
Notices shown when submitting signup form via signup.php

### ISSUE THREAD

**Issue by cwsoft** [WBCE/WebsiteBaker_CommunityEdition#246]
If frontend signup is activated, a lot of notices are shown (E_ALL, E_EVERYTHING) after the signup.php form is submitted. This is most likely due to not initialized variables and constants during setup.

Error happens with the old and the new signup.php file for both WBCE branches (1.1.x and 1.2.x).

**Comment by NorHei** [comment]
You have some notices for me ?

**Comment by cwsoft** [comment]
Here we are ... [notices.txt](https://github.com/WBCE/WebsiteBaker_CommunityEdition/files/906738/notices.txt)

**Comment by NorHei** [comment]
Does it work to create the user ?

**Comment by NorHei** [comment]
this looks like class WB is not loaded or initialized  at all

**Comment by cwsoft** [comment]
No the user is not created and the error message is couldn´t send email contact site admin.

**If you want to test it on a local server, just follow these steps:**
 1. download latest WBCE 1.1.x or 1.2.x from Github
 2. set error reporting E_EVERYTHING or E_ALL
 3. create a dummy group (e.g. test)
 4. assign signup_group in settings to test
 5. log out and access localhost/wbce/acount/signup.php
 6. fill in user details and hit create user button

**Comment by NorHei** [comment]
Hmmm , exactly what i did , and i recieved the login email , and users where created . 

Only had one notice :   
Notice: Undefined property: wb::$page_id in /var/www/...../framework/frontend.functions.php on line 468

For now it looks like class WB is loaded twice, once as class WB whith wrong parameters in singup2.php
And once in index.php

**Comment by NorHei** [comment]
I am not sure if this fixes it completely , so please test !

In my test enviroment i had no more issues ....

**Comment by NorHei** [comment]
please reopen if anything occurs
