### ISSUE TITLE
Strange resize effect with Flat Theme in Firefox

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#247]
When loading any backend site, all fonts are smoothly resized (they become approx. 5% smaller). 
Tested with Firefox 52.0.2 and Win 8.1

**Comment by NorHei** [comment]
http://www.zdnet.de/88285224/firefox-52-schuetzt-vor-font-fingerprinting/??

**Comment by instantflorian** [comment]
Problem was caused by the missing OPF filters, does not appear any more
