### ISSUE TITLE
Call to undefined method admin::user_id() when accessing Droplets Admin-Tool 

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#25]
1. Create a group and grant access to admintools to it
2. create a user and add him to the test group
3. login as test user
4. click on Admin-Tools / Droplets

=>  Fatal error: Call to undefined method admin::user_id() in /var/www/.../modules/droplets/tool.php on line 50
This does not happen if user is in administration group (group-ID 1)

**Comment by NorHei** [comment]
to me this looks like class admin is  not loaded?

**Comment by NorHei** [comment]
oh seems like you already on it

**Comment by NorHei** [comment]
nah cant be class admin ?

**Comment by NorHei** [comment]
I simply replaced tha non existing user_id() whith get_user_id(),
errors is gone now .

This must be a pretty  old bug, as its the same on even 2.8.2.

**Comment by NorHei** [comment]
the more i surf the code again i think the whole concept somehow sucks...:-(

**Comment by webbird** [comment]
Uhm that is the droplets 1.70 version that never made it into WB... but I just extended it, I did not touch the things already there...
What concept sucks?

**Comment by NorHei** [comment]
the whole concept to build the backend pages

**Comment by NorHei** [comment]
its somehow twisted ...

**Comment by webbird** [comment]
Have you committed your fix?

**Comment by NorHei** [comment]
take a look into the forum there maybe some more things be wrong

**Comment by NorHei** [comment]
shall i commit this for now  and we take a look at the other problem ?

**Comment by NorHei** [comment]
closing this
