### ISSUE TITLE
Missing icons in CKE

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#250]
Where have they gone?
![icons](https://cloud.githubusercontent.com/assets/1433754/24839959/1fb1d0d0-1d64-11e7-852a-655c1f85dd3a.jpg)
So if I uninstall CKE and re-install CKE 4.6.2.2 they are there
![afterreinstall](https://cloud.githubusercontent.com/assets/1433754/24839962/2faaa5f2-1d64-11e7-8cf2-4bd2dac7cbeb.jpg)
o_O

**Comment by NorHei** [comment]
https://github.com/WBCE/WebsiteBaker_CommunityEdition/pull/237

Please have a word whith colinax , maybe via pm in forum

**Comment by Colinax** [comment]
I have tested it and have not found any problems. It looks as if it is a problem with your test environment.

**Comment by instantflorian** [comment]
Sorry, but the error occurs as well on a Alfahosting Shared hosting webspace with PHP 7.0.17 as well as on bplaced with PHP 5.5.21, so it seems not to be a problem with my test environement, and, as I stated before, the error disappears when deinstalling / reinstalling CKE 4.6.2.2. So I guess there are just some files missing in the WBCE core installation files.

**Comment by instantflorian** [comment]
Yep, it's an issue with the codemirror plugin e.g. spelling (only lowercase vs camel case)
![codemirror](https://cloud.githubusercontent.com/assets/1433754/24840845/d66d0c2a-1d75-11e7-9698-f755e81380a9.jpg)

**Comment by Colinax** [comment]
Ok, thanks for the information. I found the reason for this Problem. I'll fix it tomorrow

**Comment by Colinax** [comment]
This problem was caused by the merge. I think that even more problems of this kind are present.

To solve it, NorHei or cwsoft must delete the whole CKE module and re-include it from a fresh Standard Edition Zip folder.

**Comment by instantflorian** [comment]
Strange. I did this, but the problem remains. I guess because I'm on a 
windows machine which does not make difference between capitals and 
small letters in file names. So anybody else has to try it again :(

**Comment by Colinax** [comment]
Have you overwrite the files with Github Desktop?

If so, this way does not work.

**Comment by Colinax** [comment]
You must completely remove the CKE module and synchronize it with 1.2.

Some seconds later you can add the fresh CKE and synchronize it again with 1.2.

This way works fine, and you habe no problem with the spelling of the file names.

**Comment by instantflorian** [comment]
That did the trick, problem solved. Thank you!
