### ISSUE TITLE
Module installer ignores module precheck.php files (multi-packages only)

### ISSUE THREAD

**Issue by cwsoft** [WBCE/WebsiteBaker_CommunityEdition#253]
The multi-module-installer introduced with 1.2.x ignores the modules **precheck.php** file if a multi-package-installation archive is installed (single modules still work). 

**Root cause:** The multi-module-installer extracts the individueal modules to /temp/unzip/mod_folder_N/. The Precheck Routine however only searches for precheck.php files located in /temp/unzip/.

**Comment by NorHei** [comment]
Just asking myself what would happen if you add just one precheck file to the folder collections root ?
Having multiple precheck would just cause chaos if they are not perfectly synchronized and modules got installed in strict order.
