### ISSUE TITLE
Set redirect time (System Settings) to 1500 ms for final release

### ISSUE THREAD

**Issue by cwsoft** [WBCE/WebsiteBaker_CommunityEdition#254]
Actual redirect time (Settings->System Settings) is set to 500ms (0,5s) which is way too fast to read the success or error messages before beeing redirected. Guess this was done for testing purposes.

The value should be set to 1500ms (1,5s) for the final 1.2.x release as done 1.1.x.

**Comment by NorHei** [comment]
Actually you dont need to read the Success message ... for what ?
The failure message does not reload

**Comment by cwsoft** [comment]
Following this logic, we shouldn't show success messages at all. 

The 0,5s are too short to get an idea of the messages content. If a status message pops up, users should get enough time to scan the message to get an idea of whats going on. On some errors (modules) there is an redirect to another page in case an error pops up. So we should reset this to the value used in WBCE 1.1.x.

**Comment by NorHei** [comment]
Simply change it in install db , i realy do not care.

Am 22.04.2017 um 11:22 schrieb Christian Sommer:
> Following this logic, we shouldn't show success messages at all.
>
> The 0,5s are too short to get an idea of the messages content. If a status message pops up, users should get enough time to scan the message to get an idea of whats going on. On some errors (modules) there is an redirect to another page in case an error pops up. So we should reset this to the value used in WBCE 1.1.x.
>

-- 
Norbert Heimsath
Mergelstraße 25
45478 Mülheim an der Ruhr
0208 55 792
