### ISSUE TITLE
Wrong deleting of users

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#26]
1. create a new usergroup
2. create a user 
3. assign her to the new user group + save
4. assign her to the administrative group + save
5. delete test usergroup
=> The user, although actually assigned to the not deleted admin user group, will be completely deleted nevertheless! Not only switched to "inactive". The account is GONE. DEAD. AWAY. ERASED!
This is a very huge and nasty bug, nearly a catastrophe. Imagine what happens if you change your user concept and delete plenty of users by mistake.

**Comment by NorHei** [comment]
A quick look at the Source tells me that this "Feature" is 100% Intentional ... at least by DV's intentions :-(

admin/goups/groups.php Line 186
```php
// Delete users in the group
				$database->query("DELETE FROM `".TABLE_PREFIX."users` WHERE `group_id` = '".$group_id."'");
				if($database->is_error()) {
					$admin->print_error($database->get_error());
				} else {
					$admin->print_success($MESSAGE['GROUPS_DELETED']);
				}
```

To really solve this problem we cannot simply deactivate this . If i simply deactivate the users will keep their groups set to non existing groups. If the user only got one Group, what is the Group we assing him ? What happens if a user does not have a group? If he has Multiple groups we can assign him to another , but what hapens if he has only one .

**Comment by NorHei** [comment]
If we deactivate em , possibly thousands of users on a site suddenly get deactivated ...

**Comment by webbird** [comment]
Suggestion: Before deleting a group, count the members. If member count > 0, do not allow to delete the group.

**Comment by NorHei** [comment]
.... hmmm good idea

**Comment by webbird** [comment]
Easiest way I think.

**Comment by NorHei** [comment]
is there a dedicated function to count the members of a group in WB ?

**Comment by webbird** [comment]
We have one in BC, dunno if it exists in WB... wait a second...

**Comment by webbird** [comment]
Cannot find it in WB, but it's a quite simple statement:

    'SELECT * FROM `:prefix:users` WHERE group_id=:id'

**Comment by NorHei** [comment]
hmm we dont have a message for group not empty ...

**Comment by NorHei** [comment]
I go an fix this tomorrow morning ... good idea , or maybe if you have time to fix it now ?

**Comment by NorHei** [comment]
off to work now ...cu

**Comment by webbird** [comment]
I'll try to fix it.

**Comment by webbird** [comment]
Please test.

**Comment by NorHei** [comment]
runs smooth for me

**Comment by webbird** [comment]
Okay, so ...
