### ISSUE TITLE
confusing messages when deleting a group

### ISSUE THREAD

**Issue by marmotwb** [WBCE/WebsiteBaker_CommunityEdition#28]
[This](https://github.com/WBCE/WebsiteBaker_CommunityEdition/commit/3d131b4cac88089f1b466073d157e92dc2684750) solved issue #26. To me this now looks like users never get deleted automatically when deleting a group.
But when deleting a group with users assigned, the admin first gets the message that users of that group will be deleted. Then saving runs into an error because there are users assigned to the group. That's not logical. The message should be canged.
It would be even more professional if the popup says that thre are still users in that group and therefore saving is not allowed.

**Comment by webbird** [comment]
Seems I forgot that popup.

**Comment by NorHei** [comment]
Can you fix it ?

**Comment by NorHei** [comment]
Got it done for german and english
