### ISSUE TITLE
Repair buggy group settings in user Table 

### ISSUE THREAD

**Issue by NorHei** [WBCE/WebsiteBaker_CommunityEdition#29]
As mentioned in #26 WB did produced a mess when changing a users group.

this should be repaired in the upgrade file : here is the code snippet that schould help , from add.php

```
// choose group_id from groups_id - workaround for still remaining calls to group_id (to be cleaned-up)
$gid_tmp = explode(',', $groups_id);
if(in_array('1', $gid_tmp)) $group_id = '1'; // if user is in administrator-group, get this group
else $group_id = $gid_tmp[0]; // else just get the first one
unset($gid_tmp);

```

**Comment by webbird** [comment]
Are you going to fix this?

**Comment by NorHei** [comment]
Not sure if i find time for this today :-( + i wanted to take a look at the advanced search as that surely needs a fix too (for group based search) 

hmmm, maybe we can do this whith a single MSQL update statement. 
If i remember right MYSQL had an IF statement

**Comment by NorHei** [comment]
Ok here is the statement:
```
UPDATE `usr_web207_3`.`wb00users2` SET `group_id` = IF (INSTR( groups_id ,","),SUBSTRING_INDEX(groups_id, ',', 1),groups_id ) WHERE 1;
UPDATE `usr_web207_3`.`wb00users2` SET `group_id` = 1 WHERE groups_id LIKE '%,1' OR groups_id LIKE '%,1,%';
```
These Two hopefully will do the job much faster than any PHP ;-)
Especially important for long user lists.

**Comment by NorHei** [comment]
Away for now , would be great if you add this to the upgrade.php , as i never worked on this file!

**Comment by marmotwb** [comment]
Suggestions by NorHei inserted into upgrade-script.php in 6b309fedf39f4d2724c6deb4c143b1152ff5fb5a.

**Comment by NorHei** [comment]
Dankeschön!!!
