### ISSUE TITLE
Hidden pages show up in navigation

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#37]
Pages with visibility setting "hidden" nevertheless shine up in navigation. Not good.

**Comment by NorHei** [comment]
if i remember right this is an old WB error too

**Comment by webbird** [comment]
It comes up every now and then. SM2 has a setting for this.

**Comment by instantflorian** [comment]
no, this error does definitively not shine up in WB, at least it does 
not in Rev. 1641 - just checked it. Neither it does in earlier versions 
of WBCE.

**Comment by instantflorian** [comment]
Why has it been changed, then?

**Comment by NorHei** [comment]
WB i such a funnie thing, letz check lates changes to show menu2

**Comment by marmotwb** [comment]
Can't confirm that bug. Just tried it.

**Comment by NorHei** [comment]
a look in the history says its only change is one run of code beautyfier....

**Comment by NorHei** [comment]
Can't confirm here. 
But i think i remember fixing something like that in one of my old forks , under certain circumstances hidden was not hidden ... Not sure if this was fixed somewhere in the 2.8.3 service packs. Itake a look at my archives.

**Comment by NorHei** [comment]
MAybe you give us acces to your testpage ?

**Comment by instantflorian** [comment]
send via forum PM

**Comment by NorHei** [comment]
for a quick test .. does this happen when logges in , not logged in , logged as Admin ?

**Comment by instantflorian** [comment]
makes no difference

**Comment by NorHei** [comment]
....hmmm there was something whith this showhidden thing

**Comment by NorHei** [comment]
Ok Fist thing i found, WB_VERSION is 1.0.0    therefore line 585 

if(version_compare(WB_VERSION, '2.7', '>=')) {

is never executed .

**Comment by NorHei** [comment]
plus there are some more wbversion if then in the module

**Comment by NorHei** [comment]
Is this really a recent version ?

**Comment by NorHei** [comment]
if i remember right there are still some more bugs in show_menu2... but lets see after this one first

**Comment by instantflorian** [comment]
> Is this really a recent version ?
Argh! No, it isn't. My mistake, I'm sorry. Closing issue.
