### ISSUE TITLE
Installer doesn't check database credentials

### ISSUE THREAD

**Issue by nibz** [WBCE/WebsiteBaker_CommunityEdition#4]
Hi there,

When i try to install WBCE and i give a wrong password i get the following message:
"Warning: mysqli_connect(): (HY000/1045): Access denied for user"
This message is not generated by the installer, i think it would be good if the installer checks the database connection before really trying to put the tables in the database.

If you need more info just ask :).

Thnx

**Comment by webbird** [comment]
We have not changed the installer...

**Comment by webbird** [comment]
I close this as I referenced it from #6, should be done there.
