### ISSUE TITLE
Fatal error: Class 'WbAuto' not found in .....\framework\initialize.php

### ISSUE THREAD

**Issue by qssocial** [WBCE/WebsiteBaker_CommunityEdition#45]
Hi
I got this message when I started INSTALL wbce (branch: master 10/22/1015)
WampServer
Apache Version :2.2.21  
PHP Version :5.3.8 
Windows 10
Fatal error: Class 'WbAuto' not found in .....\framework\initialize.php on line 39 (save php)

Thank you

OK 
when changed
initialize.php line 38 from require WB_PATH . '/framework/class.autoload.php';
on require WB_PATH . "/framework/class.autoload.php"; now working.

**Comment by NorHei** [comment]
Not sure if this is one of those strange behaviors PHP presents on different OS .. but i simply changed it. "" should be as valid as '' ... but hey its PHP :-)

Thanks for report and solution!!

**Comment by qssocial** [comment]
No problem :)
We must help each other:)

Thanks
