### ISSUE TITLE
% sign in menu or page title breaks page tree

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#47]
If a percent sign (%) is used in menu title or page title of a sub page, the page tree does not work properly any more. The tree where the critical page is located is not shown any more and other sub pages show up under the wrong element.
E.g.
- page1
-- subpage 1
-- subpage 2 with %
- page 2
etc...
=> breaks the tree.
Its just a JS bug, the pages themselves are properly created.

**Comment by marmotwb** [comment]
Problem is line 274 in page_tree.php. sprintf treats % sign as selector for replacement. So I just replaced % by its unicode representation for display in page tree.
