### ISSUE TITLE
Add install calls for additional modules in upgrade-script.php

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#48]
When updating from WB to WBCE the tables for the newly added modules are missing:
- topics
- miniform
- WB user statistics

This is currently completely missing. Using one of these modules ends up in strange error messages.

So accordingly to the droplet installation part in ugrade-script.php there must be added the check if one of the named modules is already installed and if not, the module's install.php has to be called.
Otherwise, if the modules are already installed the module's upgrade.php should be called (but only if there is no danger of data loss by this!)

**Comment by NorHei** [comment]
Need to take a look at upgrade script anyway. What a mess....:-(

**Comment by NorHei** [comment]
Problem solved .
