### ISSUE TITLE
ShortUrl: Using output_filter module directly instead of a droplet

### ISSUE THREAD

**Issue by WebDesignWorx** [WBCE/WebsiteBaker_CommunityEdition#5]
This is not really an Issue Report.
More a simple way how to do things a little bit more comfortable for the enduser who wants to use the short url feature.

Since shortUrl is shipped with the package, it woul be wiser to use an output filter directly, than using the droplet.
It's more convenient as you don't need to handle any droplet insertion in the template you use. It will work just out of the box (if .htaccess file and the short.php file are present).

Here is a way to do it:

*[root]/modules/output_filter/index.php*

around line 69, below all other filters, add:
```php
/* ### filter type: applies Ruud's ShortURL fix ########### */
	$sShortUrlFile = WB_PATH.'short.php';
	$sHtaccessFile = WB_PATH.'.htaccess';
	if (file_exists($sShortUrlFile) && file_exists($sHtaccessFile) ) {		
		$sFilterFile = $sFilterDirectory.'filterShortUrl.php';
		if (is_readable($sFilterFile)) {
			require($sFilterFile);
			$content = doFilterShortUrl($content);
		}
	}
```

then, in the directory
*[root]/modules/output_filter/filters/*
add a new file: _filterShortUrl.php_
and insert the following code:

```php
<?php

/*
 * make use of Ruud's Short Url fix without the need to apply a droplet
 * @param string $content : reference to global $content
 */
 
function doFilterShortUrl($content) {
	// $GLOBALS['wb']->preprocess($content); // this line is obsolete IMHO
	$sUrlStart = WB_URL.PAGES_DIRECTORY;
	$sUrlEnd = PAGE_EXTENSION;
	$sNewUrlStart = WB_URL;
	$sNewUrlEnd = '/';

	preg_match_all('~'.$sUrlStart.'(.*?)\\'.$sUrlEnd.'~', $content, $aLinks);
	foreach ($aLinks[1] as $sLink) {
		$content = str_replace(
			$sUrlStart.$sLink.$sUrlEnd, 
			$sNewUrlStart.$sLink.$sNewUrlEnd, 
			$content
		);
	}
	return $content;
}
```

I didn't test the code.
But that's what it should look like in theory.
Tweak and use it as you see fit.

Cheers,
Stefek

**Comment by WebDesignWorx** [comment]
on a second thought, the line:
```php

    $GLOBALS['wb']->preprocess($content);
```
may be obsolete, since one of the previous filters already handles this stuff

**Comment by webbird** [comment]
I always have an "Enhancement" label for things like these, so feel free to post suggestions as issues. :D

**Comment by NorHei** [comment]
I often have a .htaccess but i never wanted short url. 
So its absolutely mandatory to generate a contig setting for this .

Another solution would be to have the core prepared for this, and simply check if the module is installed. If its installed it can be activated automatically. 

But that leads to the consequence that the module may not be served whith the basic package as a default.  

Dependency check only on .htaccess will run us into big trouble. 

Even some bigger hosters have a basic .htaccess in their webroot.

**Comment by WebDesignWorx** [comment]
That's right, but the above solution also checks for the presence of the `short.php` in the root.

Another thing I could think of is a checkbox within the install script. If checked, a Constant **`USE_SHORT_URL`** could be defined and set to __`true`__ in the config.php (that's actually how I solved it on some of my own installations.

This solutions allows you to check whether or not **`USE_SHORT_URL`**  is defined throuout the system, also in the Backend.

Cheers,
Stefek

**Comment by NorHei** [comment]
PLEASE if you use Constants use "WB_"   So if we talk about a config option please use WB_SHORT_URL or something like that. Please dont make the same mistakes again.

**Comment by WebDesignWorx** [comment]
Feel free to adapt the code or improve upon as you see fit. 
Kind regards, 
Stefek

**Comment by NorHei** [comment]
Already added to the new output filter, give me a day or so for some more testing ot the other filters before i upload to Repository. But basically this is finished and running. 
Thanks to Stefek for the premade solution .
hmmmm.. need to add some language vars too.

**Comment by NorHei** [comment]
I wait till i uploaded it to Repo
