### ISSUE TITLE
Rework Settings

### ISSUE THREAD

**Issue by NorHei** [WBCE/WebsiteBaker_CommunityEdition#55]
Needs to be changed to run whith Settings Class.
Needs a lot of optical rework.
No different Save buttons for different Sections
It would be very nice to have tabs for different Sections.

Just do a full Review!!!

**Comment by instantflorian** [comment]
+1.
We should consider to move some of the things which are currently at admin tools towards the general settings. (Maintenance Mode, Captcha control, Javascript admin, all these switch things)

**Comment by NorHei** [comment]
Maybe we move all Settings to Admin Tools ?

**Comment by instantflorian** [comment]
-1. This is imho not logical. Admin tools are something else then general settings, nobody would guess to find the global configuration there. 
I think Captacha control, JS admin, Maintenance mode and secure form should be moved to the options.

**Comment by NorHei** [comment]
Just a thought , some other CMS have only more or less dynamic Settings section. Joomla for example.
This also would remove the need for different folders in the admin section and so for different settings. Maybe having an option for admintools to have an menu entry , and maybe to be not displayed under normal circumstances. That way we could gain a really good modularity in the BE , and noone ever sees a change ... and we can exange all BE elements as Modules . 

But from the usability standpoint you are right :-)

**Comment by instantflorian** [comment]
Joomla is an anti-reference for me, e.g. if anything is "like in 
Joomla", it's probably horrbile incomphrehensive and innecessary 
complicated. I would prefer sticking to the user's point of view, not 
the developer's one.
Furthermore your thought imho would mean a complete rebuild of the whole 
admin backend system, so this seems to me not worth all this trouble. I 
really think just cleaning the options page (the tab solution looks 
really good) and re-order what's a tool and what's configuration as 
described is enough.

**Comment by NorHei** [comment]
But from the usability standpoint you are right :-) !!!

**Comment by NorHei** [comment]
https://fluxbb.org/resources/mods/auto-detect-language/

Was denkst so ?
-- 
Norbert Heimsath
Mergelstraße 25
45478 Mülheim an der Ruhr
Tel: 0208 55792

**Comment by instantflorian** [comment]
hatte ich mir angeschaut - ist leider veraltet
Bei uns läuft 1.5.9





------ Originalnachricht ------
Von: "NorHei" <notifications@github.com>
An: "WBCE/WebsiteBaker_CommunityEdition" 
<WebsiteBaker_CommunityEdition@noreply.github.com>
Cc: "instantflorian" <info@meerwinck.com>
Gesendet: 23.11.2015 14:22:07
Betreff: Re: [WebsiteBaker_CommunityEdition] Rework Settings (#55)

**Comment by NorHei** [comment]
Mal getestet? Für mich siehts aus als wenn das immer noch funktionieren 
dürfte , im Forum steht auch nichts von Problemen.

Am 23.11.2015 um 15:09 schrieb instantflorian:
> hatte ich mir angeschaut - ist leider veraltet
> Bei uns läuft 1.5.9
>
>
>
>
>
> ------ Originalnachricht ------
> Von: "NorHei" <notifications@github.com>
> An: "WBCE/WebsiteBaker_CommunityEdition"
> <WebsiteBaker_CommunityEdition@noreply.github.com>
> Cc: "instantflorian" <info@meerwinck.com>
> Gesendet: 23.11.2015 14:22:07
> Betreff: Re: [WebsiteBaker_CommunityEdition] Rework Settings (#55)
>
>  >https://fluxbb.org/resources/mods/auto-detect-language/
>  >
>  >Was denkst so ?
>  >--
>  >Norbert Heimsath
>  >Mergelstraße 25
>  >45478 Mülheim an der Ruhr
>  >Tel: 0208 55792
>  >—
>  >Reply to this email directly or view it on GitHub.
>  >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WBCE/WebsiteBaker_CommunityEdition/issues/55#issuecomment-158941220>.
>

-- 
Norbert Heimsath
Mergelstraße 25
45478 Mülheim an der Ruhr
Tel: 0208 55792

**Comment by NorHei** [comment]
JEEEEHA ... finally done !!!
64f047cd19697a168f3e16a52f35d3e3bd9caf6f
And follow ups.
