### ISSUE TITLE
Wrong (absolute) path in /media/index.php

### ISSUE THREAD

**Issue by webbird** [WBCE/WebsiteBaker_CommunityEdition#57]
In difference to all other index.php files, the one in the media-subfolder contains an absolute URL. While this is no problem in most cases, it can result in one after moving the page to a different domain.

**Comment by NorHei** [comment]
Simply make it the usual ../ ?

**Comment by webbird** [comment]
My first idea, too, but I don't know why this was changed from WB 2.8.2 to 2.8.3?

**Comment by NorHei** [comment]
Thats a risk we need to take , as changes in WB are extremely poor documented  :-(
