### ISSUE TITLE
Update Jquery and Jquery UI

### ISSUE THREAD

**Issue by NorHei** [WBCE/WebsiteBaker_CommunityEdition#58]
The Jquery and Jquer UI versions of WEbsitebaker are very old , they really need some upgrade.

**Comment by qssocial** [comment]
The latest version 2.x works correctly. I tested.

**Comment by NorHei** [comment]
Thx for testing ! 
We still need to test some modules. For example Fancybox needed some fixing to be functional whith Jquery2.x. There are other Modules that need testig too. 

If someone finds some that make some trouble they get fixed in the upgrade process too !

**Comment by qssocial** [comment]
Hi,
I have 
jQuery v2.1.4
jQuery UI - v1.11.4 
and works correctly.

for ResponsiveFG and Topics you must change jcrop
https://github.com/tapmodo/Jcrop/archive/master.zip
:)

**Comment by NorHei** [comment]
Extremely good to know !

I guess thats going into next release :-)
For this we are on feature freeze.

Maybe you actually like to take care of this 

Hmm,  maybe you like to take care of adding this?

**Comment by NorHei** [comment]
Maybe you even got a nice idea to replace YUI in the Pagetree ?

**Comment by NorHei** [comment]
Updated(Downgraded) Jquery to  1.12.0 in 1.2.x   as its the most compatible version and is API compatible whith  Version 2 .   Jquery UI is  v1.11.4    and we offer  jQuery Migrate v1.3.0. 
As Migrate helps whith compatibility of old scripts plus it helps to Migrate those scripts as it gives a lot of hints on how to port them. 

Backend loads Jquery + UI + Migrate by default so there is no reason for modules to load this again. 
In addition BE loads Font Awesome by default too.
