### ISSUE TITLE
Genrate a Jquery UI theme for the backend Templates 

### ISSUE THREAD

**Issue by NorHei** [WBCE/WebsiteBaker_CommunityEdition#60]
Someone needs to generate a theme  for WBFlat and Argos theme .
http://jqueryui.com/themeroller/

**Comment by marmotwb** [comment]
possible double of #16

**Comment by NorHei** [comment]
LEts close em both when its done ;-)

**Comment by NorHei** [comment]
http://www.jque.re/plugins/effects-ui/jquery.ui.bootstrap/
Put iit here so i dont forget
