### ISSUE TITLE
Notice: Undefined variable: menu_link in ...\wbce\admin\pages\page_tree\page_tree.php on line 161

### ISSUE THREAD

**Issue by qssocial** [WBCE/WebsiteBaker_CommunityEdition#65]
Hello,
when logged in to backend as a user I got a message in pages:
Notice: Undefined variable: menu_link in ...\wbce\admin\pages\page_tree\page_tree.php on line 161

Please initiate menu_link as below
$menu_link = false;	
// manage SECTIONS and DATES Icons -->
$canManageSections 	= (MANAGE_SECTIONS == 'enabled' && $admin->get_permission('pages_modify') == true && $can_modify == true)?true:false;	

Thank you

**Comment by NorHei** [comment]
I have to say thank you ! ;-)
