### ISSUE TITLE
Odd semicolon

### ISSUE THREAD

**Issue by NorHei** [WBCE/WebsiteBaker_CommunityEdition#67]
admin\settings\index.php
Ln:237 = Odd semicolon
Ln:249 = Odd semicolon

WTF!!!
Does anyone have an idea whats that ?
```
if(($addon['directory'] == DEFAULT_TEMPLATE) ? $selected = ' selected="selected"' : $selected = '');
```
The term inside sets $selected, but the if does nothing ???

**Comment by webbird** [comment]
The context is:

            if(($addon['directory'] == DEFAULT_TEMPLATE) ? $selected = ' selected="selected"' : $selected = '');
            $template->set_var('SELECTED', $selected);
            $template->parse('template_list', 'template_list_block', true);

So it sets the "selected" attribute to the select option if the current addon is the default template.

**Comment by webbird** [comment]
Strange syntax anyway.

**Comment by webbird** [comment]
Can be done with less database queries, too.

**Comment by NorHei** [comment]
Indeed the syntax is very strange.
Simply removing the if () should do exactly the same .

```
($addon['directory'] == DEFAULT_TEMPLATE) ? $selected = ' selected="selected"' : $selected = '';
```

**Comment by NorHei** [comment]
but sometimes the good old WB has surprises for those who think "it should be the same" ;-)

**Comment by webbird** [comment]
I would write it some more differently:

    $selected = ($addon['directory'] == DEFAULT_TEMPLATE) ? ' selected="selected"' : '';

**Comment by webbird** [comment]
Okay, in fact I would rewrite the whole thing. ;)

**Comment by NorHei** [comment]
Actually this thing is going to be entirely replaced sooner or later...

**Comment by webbird** [comment]
I am sure _all_ things will be replaced at their time...

**Comment by NorHei** [comment]
How philosophic.... :-)

**Comment by webbird** [comment]
I'm always philosophic on fridays...

**Comment by NorHei** [comment]
This will do for now .

**Comment by NorHei** [comment]
Apter applying this patch i found that the Theme switcher in the BE did not function properly and i did some research.
```
// this nasty construct seems to rely on the concept that if the first expression in an if() is false , all othere aren't executed
if(($addon['directory'] == DEFAULT_TEMPLATE) ? $selected = ' selected="selected"' : $selected = '');
```
