### ISSUE TITLE
ELSEIF have same conditions

### ISSUE THREAD

**Issue by NorHei** [WBCE/WebsiteBaker_CommunityEdition#68]
Another very strange error 

admin\pages\settings\settings.php
Ln:331 = If and ELSEIF have same conditions
Ln:334 = If and ELSEIF have same conditions

It seems that the code has been changed to use page_code instead of page

```
                if($results_array['page_code'] == $page['page_code'])
                {
                    $template->set_var('SELECTED', ' selected="selected"');
                } elseif($results_array['page_code'] == $page['page_code'])
                {
                    $template->set_var('SELECTED', ' disabled="disabled" class="disabled"');
                    $list_next_level=false;
                } elseif($can_modify != true)
```

In old 2.8.0 this was 
```
	                if($results_array['parent'] == $page['page_id']) {
				$template->set_var('SELECTED', ' selected="selected"');
			} elseif($results_array['page_id'] == $page['page_id']) {
				$template->set_var('SELECTED', ' disabled="disabled" class="disabled"');
				$list_next_level=false;
			} elseif($can_modify != true) {


```

Maybe one of the old WB pros has any idea why this was changed. i Found this really strange!!!

Thx to Evaki for reporting this .

**Comment by webbird** [comment]
I remember that I've fixed alot of such strange thingies when working on BC 1.x. I also found an if() with 4 OR's that all had the same condition...

**Comment by webbird** [comment]
Seems to be for mod_multilingual...

    // workout field is set but module missing
    $TEXT['PAGE_CODE'] = empty($TEXT['PAGE_CODE']) ? 'Pagecode' : $TEXT['PAGE_CODE'];
    $template->set_var( array(
            'DISPLAY_CODE_PAGE_LIST' => ' id="multi_lingual"',
            'TEXT_PAGE_CODE' => '<a href="'.WB_URL.'/modules/mod_multilingual/update_keys.php?page_id='.$page_id.'">'.$TEXT['PAGE_CODE'].'</a>'
        )
    );

**Comment by NorHei** [comment]
Maybe you like to take a quick look into that old svn ?
And maybe add some of those  here ???

Am 25.11.2015 um 13:26 schrieb Bianka Martinovic:
> I remember that I've fixed alot of such strange thingies when working on
> BC 1.x. I also found an if() with 4 OR's that all had the same condition...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WBCE/WebsiteBaker_CommunityEdition/issues/68#issuecomment-159592713>.
>

-- 
Norbert Heimsath
Mergelstraße 25
45478 Mülheim an der Ruhr
Tel: 0208 55792

**Comment by webbird** [comment]
I'm sorry, but this is not possible, as we removed most methods and replaced them with our owns.

**Comment by marmotwb** [comment]
To me it seems that this lines were introduced in wb2.8.1: https://github.com/marmotwb/2.8.x/commit/58bacd649b303e1686fbb7444fc4dd8b862cb4bd#diff-63f673c8868922a59357e992336fff85
Maybe you mixed it up as around line 424 there is a similar construct.
Of course you can delete the second elseif clause as it is never executed. I guess it was just copied from the section around line 424 and than not patched perfectly.

**Comment by NorHei** [comment]
made it look like the one around  Line 429.. lets see what test results are .

**Comment by NorHei** [comment]
No problems so far , closing this
