### ISSUE TITLE
Include multilingual patch

### ISSUE THREAD

**Issue by webbird** [WBCE/WebsiteBaker_CommunityEdition#7]
http://forum.wbce.org/viewtopic.php?id=17

**Comment by NorHei** [comment]
As far as i remembered we decided to leave this as a module ?

**Comment by webbird** [comment]
Don't know

**Comment by NorHei** [comment]
MAhlzeit

HAben grade ein kleines Problem mit WB profiles, Florian hat da ein 
Module directory zusammengebaut, und das schaut auch nicht schlecht aus !

http://addons.wbce.org/module.php

Nun habe wir im Frontend allerdings das problem das das Timeout für 
ddeien Tokens , sagen wir mal SEHR knapp ist.  Immer wenn ich ma einen 
Moment nachdenke bekomme ich eine Invalid Token Meldung.

Kann man das irgentwo einstellen ? Für die FTAN steht die Zeit auf 7200 
Sekunden.

Schöne Grüße Norbert

Am 05.08.2015 um 13:31 schrieb Bianka Martinovic:
> Don't know
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WBCE/WebsiteBaker_CommunityEdition/issues/7#issuecomment-127963194>.
>

-- 
Norbert Heimsath
Mergelstraße 25
45478 Mülheim an der Ruhr
Tel: 0208 55792

**Comment by webbird** [comment]
Am 07.08.2015 um 11:55 schrieb NorHei - notifications@github.com:
>
>
> Nun habe wir im Frontend allerdings das problem das das Timeout für
> ddeien Tokens , sagen wir mal SEHR knapp ist. Immer wenn ich ma einen
> Moment nachdenke bekomme ich eine Invalid Token Meldung.
>
> Kann man das irgentwo einstellen ? Für die FTAN steht die Zeit auf 7200
> Sekunden.
>
Das liegt garantiert nicht am Timeout, das muß ein anderes Problem sein.

**Comment by NorHei** [comment]
Hi there
https://github.com/WBCE/WebsiteBaker_CommunityEdition/commit/8e37b0e72f3c58c1010f1f33689f64750abef12a

did you add the new field to upgrade.php?

as i cannot find it ?

sincerly yours
Norbert



-- 
Norbert Heimsath
Mergelstraße 25
45478 Mülheim an der Ruhr
Tel: 0208 55792

**Comment by webbird** [comment]
I am confused, as the comments here are mixed up. :/

**Comment by NorHei** [comment]
hmm thats really mixed up... damm

**Comment by NorHei** [comment]
Florian, reported, that the timeout problem was only a temporary one.  

Mod_multilingual is moved in the modules directory, and stays a module. It has hooks in the core that enables all core functionality as soon as the module is installed.
