### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#74]
New install (not upgrading) fails, the screen is smeared with big, bold error messages. 

Error copying file: email.htt to the templates folder. Please move the files from the defaults folder manually to the templates folder!
Error copying file: email_field_value.htt to the templates folder. Please move the files from the defaults folder manually to the templates folder!
Error copying file: form_EN_callme (HTML5).htt to the templates folder. Please move the files from the defaults folder manually to the templates folder!
Error copying file: form_EN_callme.htt to the templates folder. Please move the files from the defaults folder manually to the templates folder!
Error copying file: form_EN_contactform (HTML5).htt to the templates folder. Please move the files from the defaults folder manually to the templates folder!
Error copying file: form_EN_contactform.htt to the templates folder. Please move the files from the defaults folder manually to the templates folder!
Error copying file: form_EN_full_contactform (HTML5).htt to the templates folder. Please move the files from the defaults folder manually to the templates folder!
Error copying file: form_EN_full_contactform.htt to the templates folder. Please move the files from the defaults folder manually to the templates folder!
Error copying file: form_EN_job_application_with_resume_upload.htt to the templates folder. Please move the files from the defaults folder manually to the templates folder!
Error copying file: form_EN_mini_contactform (HTML5).htt to the templates folder. Please move the files from the defaults folder manually to the templates folder!
Error copying file: form_EN_mini_contactform.htt to the templates folder. Please move the files from the defaults folder manually to the templates folder!
Error copying file: form_NL_bel_me_terug (HTML5).htt to the templates folder. Please move the files from the defaults folder manually to the templates folder!
Error copying file: form_NL_bel_me_terug.htt to the templates folder. Please move the files from the defaults folder manually to the templates folder!
Error copying file: form_NL_contactformulier (HTML5).htt to the templates folder. Please move the files from the defaults folder manually to the templates folder!
Error copying file: form_NL_contactformulier.htt to the templates folder. Please move the files from the defaults folder manually to the templates folder!
Error copying file: form_NL_mini_contactformulier (HTML5).htt to the templates folder. Please move the files from the defaults folder manually to the templates folder!
Error copying file: form_NL_uitgebreid_contactformulier (HTML5).htt to the templates folder. Please move the files from the defaults folder manually to the templates folder!
Error copying file: form_NL_uitgebreid_contactformulier.htt to the templates folder. Please move the files from the defaults folder manually to the templates folder!
Error copying file: form_nl_mini_contactformulier.htt to the templates folder. Please move the files from the defaults folder manually to the templates folder!

**Comment by instantflorian** [comment]
Reason: The empty "templates" directory is missing

**Comment by instantflorian** [comment]
https://github.com/WBCE/WebsiteBaker_CommunityEdition/commit/e31a8eb7b45a36314b22ce8557d077133bf80967

**Comment by NorHei** [comment]
Welches Template directory ?
/tempalates/ ist doch normalerweise voll ?

Welches kopiert der denn noch ?

Am 08.12.2015 um 13:28 schrieb instantflorian:
> Reason: The empty "templates" directory is missing
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WBCE/WebsiteBaker_CommunityEdition/issues/74#issuecomment-162866470>.
>

-- 
Norbert Heimsath
Mergelstraße 25
45478 Mülheim an der Ruhr
Tel: 0208 55792

**Comment by NorHei** [comment]
Nochmal ein RC versuchen ?

Am 08.12.2015 um 13:56 schrieb instantflorian:
> Closed #74
> <https://github.com/WBCE/WebsiteBaker_CommunityEdition/issues/74>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WBCE/WebsiteBaker_CommunityEdition/issues/74#event-485602485>.
>

-- 
Norbert Heimsath
Mergelstraße 25
45478 Mülheim an der Ruhr
Tel: 0208 55792
