### ISSUE TITLE
Cleanup old language files

### ISSUE THREAD

**Issue by webbird** [WBCE/WebsiteBaker_CommunityEdition#8]
WB still has language files from very (!) old versions that should be cleaned.

http://forum.wbce.org/viewtopic.php?id=20

**Comment by NorHei** [comment]
Err, if you took alook into the repo, this is already done :-)
Hopefully all old language vars removed from  core .... took me a few hours.
Only the file is still there, maybe for module compatibility. but it simply can be removed as the loader checks for its presence and only tries to load it when its present.

**Comment by webbird** [comment]
Wasn't linked here. ;) You can reference issues by adding "#<num>" to the commit message, where <num> is the number of the issue. (Without the quotes.)

**Comment by NorHei** [comment]
For this version the compatibility file stays in WBCE , next version it is removed from core and available as download in modules and plugins. So if a module requires old language vars you can simply copy it in your language folder and the core will recognize and load it.
