### ISSUE TITLE
Installation fails with a blank screen

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#80]
Current master: After submitting save.php shows only a blank screen, no error messages whatsorever
PHP 5.5.30 & PHP 7

**Comment by NorHei** [comment]
What does the Error Log of the server say ?
Set error handling in .htaccess . 
OR maybe directly in the code!

Where can i take a look as i just installed it here ... whithout any trouble?

Is it the latest Master ? as i had a similar problem that led to e5168497d1a32d2a93cc4369b88064e3b8c52952

**Comment by NorHei** [comment]
If its a local server you can even set error handling in the php.ini

**Comment by instantflorian** [comment]
Error reporting is on, I checked this. Unfortunately I'v no access to 
error logs, its a shared host.
Actually the installation works, it seems as if  there's just no 
redirect to the login screen.

------ Originalnachricht ------
Von: "NorHei" <notifications@github.com>
An: "WBCE/WebsiteBaker_CommunityEdition" 
<WebsiteBaker_CommunityEdition@noreply.github.com>
Cc: "instantflorian" <info@meerwinck.com>
Gesendet: 26.12.2015 09:26:23
Betreff: Re: [WebsiteBaker_CommunityEdition] Installation fails with a 
blank screen (#80)

**Comment by instantflorian** [comment]
checked, fixed with https://github.com/WBCE/WebsiteBaker_CommunityEdition/commit/ef1d3c9b4ec9ded7deb877662be7c53bc54dd5b3
Thanks
