### ISSUE TITLE
JS error caused by wbstats frontend.js 

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#81]
wbstats  	0.2.0-beta.1
WBCE 1.2.0-beta1 with default WBCE FE template

Zeitstempel: 26.12.2015 09:55:39
Fehler: TypeError: $(...).poshytip is not a function
Quelldatei: .../modules/wbstats/frontend.js
Zeile: 2
=> any other frontend javascript is not longer executed (i.e. navigation)

**Comment by NorHei** [comment]
i am on it , funny thing is that this is the part that should not have changed :-)

**Comment by NorHei** [comment]
do you have a live page where in  can take a look ?

**Comment by NorHei** [comment]
Done
