### ISSUE TITLE
Smaller design reworks of installer/updater

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#82]
- remove WB classic colors
- insert current WBCE logo & claim
- remove useless/dangerous default values ("root", "admin")

**Comment by marmotwb** [comment]
possible duplicate of issue #6;
might be a good iedea to work on older issues before opening new "lets make code nicer" issues

**Comment by instantflorian** [comment]
Issue #6 is a complete rework which is quite an effort.
This issue is just a reminder (for me, see assignment) to remove the old 
claim and just change a line or two in the stylesheet. So I would not 
call this a duplicate.

**Comment by NorHei** [comment]
Admin is ok as username for the Admin,  i think ?

**Comment by instantflorian** [comment]
No, it's not. It's too easy to guess and a probable security flaw. If 
you use "admin", hackers just have to guess the password.
I removed the default value from the installer therfor.

**Comment by NorHei** [comment]
how far are you whith this ?

**Comment by instantflorian** [comment]
The changes mentioned above are done (since Jan 6, 2016), so I close this issue.
