### ISSUE TITLE
Install and short_url

### ISSUE THREAD

**Issue by qssocial** [WBCE/WebsiteBaker_CommunityEdition#83]
Hi,

I found a mistake during installation git master:
output filter / install.php
Line 35 include ("info.php")
add ";"

For SHORT_URL:
Class.admin add
line 102
add
if (OPF_SHORT_URL) {$ view_url = WB_URL. $ row ['link']; }

view.php menu_link
add
line 56 
if (OPF_SHORT_URL) {$ target_url = WB_URL. $ target_page_link. $ anchor; }

Thanks for adding SHORT_URL

Krzysztof

**Comment by NorHei** [comment]
Output filter install fixed .
view.php menu_link , added 

I thought the output filter would take care of the thing in admin?

Maybe you have an idea how to move the content of the Short.php file into a preinit.php or initialize.php of a module ?
So the short.php could be removed ...

**Comment by NorHei** [comment]
ba953c9

**Comment by qssocial** [comment]
Admin module turn off/on definition (shorturl,...) plus management sections .htaccess
A simple module that generates a list of .htaccess section on the fly

ID, SectionName, SectionValue, WBDefineValue, TurnOn

1 , Short Url  , One Section below, WB_SHORTURL, 1
2 , Force www  , ......
3 , Module Gzip, .......
etc

loop
if TurnOn == 1 add section to new .htaccess  plus the definition of other settings.



My .htaccess

<IfModule mod_rewrite.c>
RewriteEngine On

## If old url's are called directly - redirect to short url version
RewriteCond %{REQUEST_URI} !/pages/intro.php
RewriteCond %{REQUEST_URI} /pages
RewriteRule ^pages/(.*).php$ /$1/ [R=301,L]

## Send the request to the short.php for processing
RewriteCond %{REQUEST_URI} !^/(pages|admin|framework|include|languages|media|account|search|temp|templates/.*)$
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^([\/\sa-zA-Z0-9._-]+)$ short.php?_wb=$1 [QSA,L]
## end section short url

#Force www:
#RewriteEngine on
#RewriteCond %{HTTP_HOST} ^example.com [NC]
#RewriteRule ^(.*)$ http://www.example.com/$1 [L,R=301,NC]

#Force non-www:
#RewriteEngine on
#RewriteCond %{HTTP_HOST} ^www\.example\.com [NC]
#RewriteRule ^(.*)$ http://example.com/$1 [L,R=301] 

## make google_sitemap.php visible as sitemap.xml
#RewriteRule ^sitemap.xml$ /google_sitemap.php [L]

## uncomment (remove #) the next three lines to rewrite host to include www
#RewriteCond %{HTTP_HOST} !^www\.               [NC]
#RewriteCond %{HTTP_HOST} ^([^.]+\.[a-z]{2,6})$ [NC]
#RewriteRule ^(.*)$       http://www.%1/$1      [R=301,L]

# Don't fix direct file links
#RewriteCond %{REQUEST_FILENAME} !-f
#RewriteCond %{REQUEST_URI} !(.*)/$
#RewriteRule ^(.*)$ $1/ [L,R=301]
# Finally, forward everything to your front-controller (index.php)
#RewriteCond %{REQUEST_FILENAME} !-f
#RewriteCond %{REQUEST_FILENAME} !-d
#RewriteRule .* index.php [QSA,L]
</IfModule>

# Apache config
#<IfModule mod_headers.c>    
#Header add Access-Control-Allow-Origin "*"
#Header add Access-Control-Allow-Headers "origin, x-requested-with, content-type"
#Header add Access-Control-Allow-Methods "PUT, GET, POST, DELETE, OPTIONS"
#</IfModule>
#
# nginx config
#if ($filename ~* ^.*?\.(eot)|(ttf)|(woff)$){
#	add_header Access-Control-Allow-Origin *;
#}

<ifModule mod_gzip.c>
mod_gzip_on Yes
mod_gzip_dechunk Yes
mod_gzip_item_include file .(html?|txt|css|js|php|pl)$
mod_gzip_item_include handler ^cgi-script$
mod_gzip_item_include mime ^text/.*
mod_gzip_item_include mime ^application/x-javascript.*
mod_gzip_item_exclude mime ^image/.*
mod_gzip_item_exclude rspheader ^Content-Encoding:.*gzip.*
</ifModule>

**Comment by NorHei** [comment]
Hey feel free to make this !!! 


But keep in mind , most people dont have access to Apache config or nginx config

**Comment by qssocial** [comment]
I know
In that case you have to change the kernel to generate links and menu2.
I will think about it.
I must first examine the generation of links.
In WBCE readily formed new modules.
Maybe something will write :) I have a few ideas.

**Comment by NorHei** [comment]
I would really like to have this  as a Module(maybe whith some hooks). The Core itself will never be based on routing.  Whith the new Preinit mechanism you can hook into initialize at a very early state(only config read and Database initiated) and basically it should be possible controll shorturl from there.    

WB(CE) compared to many, many other CMS uses accessfiles and its planed to stay this way. Accessfiles offer al lot of very nice options like having a cache file already available or running some pages even whithout a database as the file can be used as storage container.

Basically i see absolutely no reason why use mod rewrite at all . All my SEO tests i made whith and whithout mod rewrite pages , the pages whithout always won. Google often is happy to find a tree structure in the URL .  Todays SEO is all about content , add content users like and you are very likely to get good rankings.  

So basically Short URLis  running now for those who absolutely want it , all other stuff is 1.3.x  or later :-) 
 
LEts take a look at Droplets ...
For now Closing this  if you got questions about the new mechanism in WBCE (maybe for packing this into a module) you can contact me via my homepage (heimsath.org) the contact button gives all information needed :-) (Sorry page is german only )

**Comment by qssocial** [comment]
Thank Norbert
I will think about it. I agree with you about SEO and SHORTURL is not necessary but as you can see fashionable :-)
If I see some mistakes that I'll send you the information or corrections.
Now I have two weeks of hard work and I had a little time.

I think it is important now to bet on mobility. Simple Mobile Admin to be able to edit pages and so on. In a very short time.
I made a simple gallery module with the ability to add images, videos (jplayer), youtube etc. watermark, upload user, Bye is being tested. The code is ugly but it works and later on clearing it and normalize. If it unsuitable for publication this will send it to you.
Handy to be type module resources for the template. ResourceTemplate For example, you can add text, image, file etc. Easy to change the content in the template, such as address, footer, photos, or variables to control in the template.

**Comment by NorHei** [comment]
Thats one of the reason i implemented it compared to WB Classic , it looks nice .

**Comment by NorHei** [comment]
Simply leave me a mail at norbert@heimsath.org when you got some time .
