### ISSUE TITLE
small correction for wbstats frontend.js

### ISSUE THREAD

**Issue by qssocial** [WBCE/WebsiteBaker_CommunityEdition#87]
Hi
Uncaught TypeError: Cannot read property 'style' of null
and 
browser.msie

before (function(e){var a=[],d=......

jQuery.browser = {};
(function () {
    jQuery.browser.msie = false;
    jQuery.browser.version = 0;
    if (navigator.userAgent.match(/MSIE ([0-9]+)\./)) {
        jQuery.browser.msie = true;
        jQuery.browser.version = RegExp.$1;
    }
})();

and change
function OnBeforeUnLoad () { document.getElementById('loading').style.display = 'block'; }
to
function OnBeforeUnLoad () { if (document.getElementById('loading') != null) { document.getElementById('loading').style.display = 'block';} }

Krzysztof

**Comment by NorHei** [comment]
c0de5b8..54a0473

Thanks alot!!
