### ISSUE TITLE
[root]/config.php showing wrong DB type

### ISSUE THREAD

**Issue by WebDesignWorx** [WBCE/WebsiteBaker_CommunityEdition#9]
Hi, the _[root]/config.php_ file shows a wrong DB type.
It says
```php
define('DB_TYPE', 'mysqli');
```

but it should be **mysql**
(as mysqli is only the communication driver that is used to exchange data with the mySql database ;-) )

Stefek

**Comment by webbird** [comment]
Oi. This is something we "inherited" from WB 2.8.3 SP 4. (./install/save.php line 280)

**Comment by WebDesignWorx** [comment]
Yes, that may be.
I remember I already reported it over there once.

**Comment by webbird** [comment]
Fixed. :)

**Comment by WebDesignWorx** [comment]
From what I see, this Constant is set once but never really asked for. It's useless, as it plays no role at all (currently at least). Or do I miss a thing?

**Comment by webbird** [comment]
I think it was for some far future purposes... anyway, it doesn't hurt to keep it. (As we also discuss to support SQLite...)

**Comment by WebDesignWorx** [comment]
I see. SQLite would be great. It's a hell lot of work, but in essence it would be cool to use this simple CMS with SQLite.
