### ISSUE TITLE
Parse error: syntax error, unexpected '}' in wbstats help.php

### ISSUE THREAD

**Issue by qssocial** [WBCE/WebsiteBaker_CommunityEdition#91]
Parse error: syntax error, unexpected '}' in D:\Programming\www\wamp22ap1\www\wbce12\modules\wbstats\help.php on line 34

Just delete line

**Comment by webbird** [comment]
Fixed.
This was caused by commenting out a code block. Maybe we should remove that block, too.
Also fixed invalid `<br/>` to valid `<br />` (note the blank)

**Comment by qssocial** [comment]
Thanks
When I have some time to check it and try to help.
