### ISSUE TITLE
Droplets module review/rework

### ISSUE THREAD

**Issue by webbird** [WBCE/WebsiteBaker_CommunityEdition#92]
As there are some bugs and improvements to do, I am going to review the complete module. Please let me know if you find something not listed here.

See also: #88

1.)
ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''); $names = array(); while ($file = readdir($folder)) { $ext=strtolower(subs' at line 1

2.)
Mark and delete creates backup.
**Remark: This is by design!** Of course, the droplet should be removed anyway.

3.)
Icons/Buttons not working without Javascript.
**Remark:** The whole WBCE backend needs Javascript, so the Droplets module requires it, too.

4.)
Modify Icon missing tooltip.

5.)
Mark a list of droplets -> Backup
    Saving: PreviousPage.php
    Security offense access denied.
Back Button -> global Droplets page

6.)
Tooltips truncated. 
**Remark:** Maybe a Flat Theme issue.

7.)
Footer links point to AMASP, but no one maintains the droplets list there.

**Comment by webbird** [comment]
6.)
What the...

*::before, [class^="web-developer"] {
[...]
    **z-index: 2147483647 !important;**
}

No wonder that it covers the tooltip...

**Comment by webbird** [comment]
5.)
Security offense
Strange code in backup_droplets.php:

    $id = intval( $admin->checkIDKEY('id', false, 'GET'));
    if ( !$id or $id != 999 )

**Comment by NorHei** [comment]
You may remove the idkey and ftan stuff completely , i readd it in correct implementation after you are done if you like .

**Comment by webbird** [comment]
Ok

**Comment by NorHei** [comment]
As the multitab implementation can be used even in get forms  we possibly can remove idkey completely.

**Comment by webbird** [comment]
1.)
Dunno where this came from, hopefully fixed.

2.)
There's now a note that deletion will create a backup automatically.

3.)
Won't fix.

4.)
Tooltip only for Comments, all others have a title attribute.

5.)
Hopefully fixed.

6.)
Flat Theme problem, fixed in backend.css.

7.)
Footer points now to new page which has to be filled.

**Comment by webbird** [comment]
**Other things done (incomplete list):**

* removed some files (manage_backups.php for example), moved functions into tool.php / functions.inc.php
* Moved all HTML to Twig templates
* renamed all methods in functions.inc.php with wbce_ prefix
* fixed SQL statements (using sprintf() etc.)
* fixed some strange code
* removed all id number / form data obfuscation, only left FTAN
* full backup no longer overwrites existing files (added datetime to filename)

**Still open:**

* Not all files are reviewed yet (upgrade.php for example)
* TESTING

**Comment by webbird** [comment]
Please make a pull to test.

**Comment by NorHei** [comment]
Fatal error: Uncaught exception 'Twig_Error_Loader' with message 'The "/var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/templates" directory does not exist.' in /var/www/web207/html/wbce_norbert_heimsath_de/modules/twig/classes/Sensio/Twig/lib/Twig/Loader/Filesystem.php:93 Stack trace: #0 /var/www/web207/html/wbce_norbert_heimsath_de/modules/twig/classes/Sensio/Twig/lib/Twig/Loader/Filesystem.php(75): Twig_Loader_Filesystem->addPath('/var/www/web207...', '__main__') #1 /var/www/web207/html/wbce_norbert_heimsath_de/modules/twig/classes/Sensio/Twig/lib/Twig/Loader/Filesystem.php(33): Twig_Loader_Filesystem->setPaths('/var/www/web207...') #2 /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php(28): Twig_Loader_Filesystem->__construct('/var/www/web207...') #3 /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/tool.php(25): require_once('/var/www/web207...') #4 /var/www/web207/html/wbce_norbert_heimsath_de/admin/admintools/tool.php(83): require('/var/www/web207...') #5 {mai in /var/www/web207/html/wbce_norbert_heimsath_de/modules/twig/classes/Sensio/Twig/lib/Twig/Loader/Filesystem.php on line 93

**Comment by NorHei** [comment]
functions.inc.php:        require_once WB_PATH.'/modules/twig/initialize.php';
Das sollte nicht nötig sein , die Datei(/modules/twig/initialize.php') wird in der framework.initialize geladen. Deswegen ist der Twig Autoloader schon von anfang an registriert. 

Die initialize.php Dateien  wenden in der haupt init geladen wenn man dem Modul in der info.php was hinzufügt.
$module_function = 'tool, initialize';

**Comment by NorHei** [comment]
Vieleicht magst aus der Funktionssammlung auch eine Klasse bauen ?

**Comment by webbird** [comment]
Also in meiner Umgebung _mußte_ ich das machen, da wurde nix automatisch geladen, obwohl ich vorher ein Update von GitHub gemacht hatte.

Und nein, ich baue keine Klasse, dann könnte ich ja gleich die aus BC nehmen... ;)

**Comment by NorHei** [comment]
hmmm viellleicht hast ja noch nen neuen bug gefunden ... ich schau mir das mal an .

**Comment by NorHei** [comment]
btw the template folder still missing , so i cannot test here :-(

**Comment by webbird** [comment]
Pls pull.

**Comment by NorHei** [comment]
pulling

**Comment by NorHei** [comment]
![screenshot - 08 01 2016 - 13 22 30](https://cloud.githubusercontent.com/assets/1908651/12197875/346bdb86-b60b-11e5-823a-627e26a82dee.png)

**Comment by webbird** [comment]
This is a fault in the DB, not in the module. If you look into the database table you'll see.

**Comment by NorHei** [comment]
Ok ... a click on the backup droplets button gives me this
```
Warning: fopen(/var/www/web207/html/wbce_norbert_heimsath_de/temp/droplets/ModifiedWhen.php): failed to open stream: Permission denied in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 133

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 135

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 136

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 137

Warning: fclose() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 138

Warning: fopen(/var/www/web207/html/wbce_norbert_heimsath_de/temp/droplets/RandomImage.php): failed to open stream: Permission denied in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 133

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 135

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 136

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 137

Warning: fclose() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 138

Warning: fopen(/var/www/web207/html/wbce_norbert_heimsath_de/temp/droplets/EditThisPage.php): failed to open stream: Permission denied in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 133

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 135

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 136

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 137

Warning: fclose() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 138

Warning: fopen(/var/www/web207/html/wbce_norbert_heimsath_de/temp/droplets/Lorem.php): failed to open stream: Permission denied in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 133

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 135

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 136

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 137

Warning: fclose() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 138

Warning: fopen(/var/www/web207/html/wbce_norbert_heimsath_de/temp/droplets/ShowWysiwyg_copy.php): failed to open stream: Permission denied in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 133

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 135

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 136

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 137

Warning: fclose() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 138

Warning: fopen(/var/www/web207/html/wbce_norbert_heimsath_de/temp/droplets/Oneliner.php): failed to open stream: Permission denied in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 133

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 135

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 136

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 137

Warning: fclose() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 138

Warning: fopen(/var/www/web207/html/wbce_norbert_heimsath_de/temp/droplets/EmailFilter.php): failed to open stream: Permission denied in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 133

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 135

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 136

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 137

Warning: fclose() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 138

Warning: fopen(/var/www/web207/html/wbce_norbert_heimsath_de/temp/droplets/ShowWysiwyg.php): failed to open stream: Permission denied in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 133

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 135

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 136

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 137

Warning: fclose() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 138

Warning: fopen(/var/www/web207/html/wbce_norbert_heimsath_de/temp/droplets/LoginBox.php): failed to open stream: Permission denied in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 133

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 135

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 136

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 137

Warning: fclose() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 138

Warning: fopen(/var/www/web207/html/wbce_norbert_heimsath_de/temp/droplets/SearchBox.php): failed to open stream: Permission denied in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 133

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 135

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 136

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 137

Warning: fclose() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 138

Warning: fopen(/var/www/web207/html/wbce_norbert_heimsath_de/temp/droplets/NextPage.php): failed to open stream: Permission denied in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 133

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 135

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 136

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 137

Warning: fclose() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 138

Warning: fopen(/var/www/web207/html/wbce_norbert_heimsath_de/temp/droplets/SiteModified.php): failed to open stream: Permission denied in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 133

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 135

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 136

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 137

Warning: fclose() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 138

Warning: fopen(/var/www/web207/html/wbce_norbert_heimsath_de/temp/droplets/SectionPicker.php): failed to open stream: Permission denied in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 133

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 135

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 136

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 137

Warning: fclose() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 138

Warning: fopen(/var/www/web207/html/wbce_norbert_heimsath_de/temp/droplets/PreviousPage.php): failed to open stream: Permission denied in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 133

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 135

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 136

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 137

Warning: fclose() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 138

Warning: fopen(/var/www/web207/html/wbce_norbert_heimsath_de/temp/droplets/ShowRandomWysiwyg.php): failed to open stream: Permission denied in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 133

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 135

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 136

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 137

Warning: fclose() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 138

Warning: fopen(/var/www/web207/html/wbce_norbert_heimsath_de/temp/droplets/ParentPage.php): failed to open stream: Permission denied in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 133

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 135

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 136

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 137

Warning: fclose() expects parameter 1 to be resource, boolean given in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 138

```

**Comment by webbird** [comment]
I can catch that error, but this does not solve the reason. Pls check the perms for the ./droplets/export subfolder.

**Comment by NorHei** [comment]
/wbce_norbert_heimsath_de/temp/droplets/ParentPage.php

sure that files exist in /temp/ ?

export set to 777 no change

**Comment by webbird** [comment]
Dunno where this comes from?

**Comment by NorHei** [comment]
functions.inc.php line 133 
the write messages are followups as there is no filehandler

**Comment by webbird** [comment]
Found the error in RandomImage droplet: The file has MAC style line endings! After converting to DOS the import works.

**Comment by webbird** [comment]
Sorry, I don't understand... ?!?

**Comment by webbird** [comment]
/wbce_norbert_heimsath_de/temp/droplets/ParentPage.php

Please check:

* The subfolder should be created by the export. To check, add an `exit` in `wbce_backup_droplets()` on line 125.
* If the subfolder exists, a new file should be created for each droplet. To check, add an `exit` after `foreach(array_values($list) as $droplet)` and count the files. (If any.)

Unfortunately, it is not easy to find why `fopen()` fails. So please check the perms of the temp folder itself.

**Comment by NorHei** [comment]
sorry away fo a few hours

**Comment by webbird** [comment]
Okay, pull after coming back.;)

**Comment by NorHei** [comment]
File mode needs to be an octal value  0777 for example not a string . 
Somtimes you need to set umask(0) before . 

Best Would be to use 
mkdir($temp_dir,OCTAL_DIR_MODE);

**Comment by NorHei** [comment]
Warning: fopen(/var/www/web207/html/wbce_norbert_heimsath_de/temp/droplets/ModifiedWhen.php): failed to open stream: Permission denied in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/functions.inc.php on line 146

But as i said, its the filemmode.

**Comment by webbird** [comment]
Which OS?

**Comment by NorHei** [comment]
When i save a Droplet this textarea is shown .  Bug or feature ?

![screenshot - 08 01 2016 - 13 36 09](https://cloud.githubusercontent.com/assets/1908651/12201239/5957184e-b623-11e5-961b-737b11445a24.png)

**Comment by NorHei** [comment]
Linux debian

**Comment by NorHei** [comment]
PHP manual states clear it needs a octal value.

**Comment by webbird** [comment]
???

bool mkdir ( string $pathname [, **int** $mode = 0777 [, bool $recursive = false [, resource $context ]]] )

**Comment by NorHei** [comment]
mkdir($temp_dir,OCTAL_DIR_MODE, true);
creates the dir recursively

**Comment by webbird** [comment]
Now I see, I accidentally used quotes... Warum sagst des nicht einfach gleich!

**Comment by NorHei** [comment]
File mode needs to be an octal value 0777 for example not a string . .... ähhh was warn das  :-))

**Comment by webbird** [comment]
Change line 129 to

if(!@mkdir($temp_dir,0770))

That should work

**Comment by NorHei** [comment]
Please use the OCTAL_DIR_MODE constant so anyone can ste its own Directory values , sometimes 0770 leads server errors or security issues .  Otherwise the poor user need to fix the modules manually,

**Comment by NorHei** [comment]
@ is not needed

**Comment by webbird** [comment]
In fact it IS needed to catch the error!

**Comment by NorHei** [comment]
what error ?

**Comment by NorHei** [comment]
there is no error when i remove the '' here-

**Comment by webbird** [comment]
Sollen wir das jetzt wirklich hier ausdiskutieren??? Da ist eine Fehlerbehandlung drin - auch mit OCTAL_dings kann es noch Fehler geben -, daher macht @ hier absolut Sinn.

        if(!@mkdir($temp_dir,OCTAL_DIR_MODE))
        {
            $err = error_get_last();
            return '<div class="alertbox error">'.
                   $MESSAGE['MEDIA_DIR_NOT_MADE'].': '.
                   $err['message'].
                   '</div>';
        }

**Comment by NorHei** [comment]
mit error_get_last(); macht das natürlich absolut sinn !

**Comment by NorHei** [comment]
ups ... german again :-)

**Comment by webbird** [comment]
I've removed some comments to keep this issue more clearly.

**Comment by NorHei** [comment]
waiting for next pull :-)

**Comment by webbird** [comment]
So let's see what we've fixed today...

* added some more error handling (temp folder creation, fopen())
* added templates folder to repository
* fixed MAC style line breaks in droplet RandomImage
* added error handling for line breaks

**Comment by NorHei** [comment]
Good Job !!

**Comment by qssocial** [comment]
copy function
line 91 functions.inc ( ? -> &)
        $url = ADMIN_URL . '/admintools/tool.php?tool=droplets?droplet_id='.$new_id;
it should be
        $url = ADMIN_URL . '/admintools/tool.php?tool=droplets&do=modify&droplet_id='.$new_id;

**Comment by webbird** [comment]
Ah, thank you, fixed it.

**Comment by qssocial** [comment]
Hi
Thank you for correct.

I made a fork for test.
https://github.com/qssocial/WebsiteBaker_CommunityEdition
View the changes.
I added CKEditor 4.5.5
jQuery 2.1.4
jquery-ui-1.11.4

wbstats - I added prefix "wbstats_" in css and improved:
links view.php, javascript functions to be compatible with jQuery 2.1.4.
I added a reset button in wbstats.

topics
I added jcrop and texts next prew.

In advancedThemeWbFlat removed and changed to links to jquery-ui.

Regards
Krzysztof Winnicki

**Comment by NorHei** [comment]
Testing it right now :-)  had trouble whith topics as it said cant create directory(uploading images) , but thats possibly my test instalations  that had too many tests . Reinstalling now , and testing again.

**Comment by qssocial** [comment]
it will be easier to test before making changes :-)

**Comment by NorHei** [comment]
Droplets is ok for me so far , closing this
