### ISSUE TITLE
Sorry but menu link and class.admin again

### ISSUE THREAD

**Issue by qssocial** [WBCE/WebsiteBaker_CommunityEdition#95]
$ !

114 class.admin                     if (OPF_SHORT_URL) {$view_url = WB_URL. $ row ['link']; }
if (OPF_SHORT_URL) {$view_url = WB_URL. $row['link']; }

57 menu link view             if (OPF_SHORT_URL) {$target_url = WB_URL. $target_page_link. $ anchor; }
if (OPF_SHORT_URL) {$target_url = WB_URL.$target_page_link. $anchor; }

I'm the same when little sleep:-)

Regards
Krzysztof

**Comment by webbird** [comment]
Should be fixed.
