### ISSUE TITLE
v1.2 - Installer errors

### ISSUE THREAD

**Issue by webbird** [WBCE/WebsiteBaker_CommunityEdition#97]
Just tried a fresh install with current snapshot and got some errors in save.php:

Notice: Undefined variable: HEADING in <path>\modules\droplets\functions.inc.php on line 32
Notice: Undefined variable: TEXT in <path>\modules\droplets\functions.inc.php on line 33
Notice: Undefined variable: imports in <path>\modules\topics\install.php on line 305
Warning: Cannot modify header information - headers already sent by (output started at <path>\modules\droplets\functions.inc.php:33) in <path>\install\save.php on line 79

Of course, error settings are set to all.

**Comment by webbird** [comment]
I should mention that the install succeeded anyway.

**Comment by NorHei** [comment]
Language Files are not loaded in Save.php ??

But i cannot find the call for functions.inc.php

This shows up cause i activaded errors in installer :-)

Ahh topics already fixed 87d84dd
