### ISSUE TITLE
wbstats frontend.css big problem

### ISSUE THREAD

**Issue by qssocial** [WBCE/WebsiteBaker_CommunityEdition#98]
Hi
Please rename the class css to only web stats (ex wbstats_full etc).
Wb Stats does conflict with css with other modules such as miform ".full" or bootstram ".container"

**Comment by NorHei** [comment]
How about you do that ?

**Comment by qssocial** [comment]
I use Miniform and Bootstrap.
Bwstats and miniform uses a class with the same name.
.full.
When I clicked on the link to the contact form I saw that changed the look.
Similarly wbstats and bootstaram uses container.
I know it recently added to wbstats css and it caused a problem.

**Comment by webbird** [comment]
Once there was a rule that all CSS classes should have a prefix which contains the module name, for example 'mod_wbstats_whatever'. We should require this for all modules and fix the class names for all modules that are bundled.

**Comment by qssocial** [comment]
I agree with you. This is what we should be. Similarly, the names of functions in javascript.
Recently I used Colorbox in my template and I had a problem because it was already used in the module colorbox. I believe that such units should be in the admin and there turned on/off.

**Comment by webbird** [comment]
It's not that easy with colorbox, as the CSS classes are defined by Colorbox itself, not the module.

**Comment by qssocial** [comment]
I mean, the colorbox  should be in the admin and with option to disable/enable.
Other custom function javascript/php/css created with the prefix should be.

**Comment by NorHei** [comment]
Whith the old frontend functions you can only choose add all module CSS/JS or none .
All or nothing , thats it.  Only real option now is install/uninstall. 
Thats the reason i started whith class Insert, where you can controll if a script is loaded, simply by setting settings and using  include.php.  So you gain granular control over scripts loaded by your module . 

For Colorbox that means BE Templateswitcher or activate/deactivate for example. 
Class insert is ready so far, missing only compatibility for old frontend.css/.js files right now.


If you both feel like changing the Classes , please start , thats a good idea !!!
Possibly i would prefer just using "wbstats_whatever" to keep it short. 
Or even better put the output in a <div class="wbstats">...</div> 

And simply define the CSS like 

.wbstats h1{some styles;}
.wbstats a {some other;}

That way you conserve the elements that you want to look like the default already defined and override other. That the way how the cascade was meant to be made.

**Comment by NorHei** [comment]
As far as i remember i already added your Patch
